### ISSUE TITLE
[Recommendation] Ears

### ISSUE THREAD

**Issue by LambdAurora** [TeamAOF/All-of-Fabric-5#1]
> Faithful fancy fashion features for fuzzy folk.

[Ears](https://www.curseforge.com/minecraft/mc-mods/ears) is a cosmetic mod which uses the unused parts of the skin texture to encode its data, which means it doesn't rely on any external server, and due to its architecture allow it to be ported to nearly any version of the game.

On servers, players will see ears features on other players if those players use an ears skin.

This is a neat mod, and great for user customization, and is really cool to use when playing with other people.

**Comment by dandin87** [comment]
I would love to see a repository of parts that would could easily merge with their skins to actually use this. Seems like everyone has to start from scratch. Is there a good place to find skins that are using these features?
