### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by bruiser28** [TeamAOF/All-of-Fabric-5#100]
When trying to smelt thalassium it says you need a furnace made of smelted the
alassium but you cant get it without said furnace
**
![image](https://user-images.githubusercontent.com/97767692/149597160-31c32b51-3fae-4ee2-bfdb-10a0698f41c6.png)
**
![image](https://user-images.githubusercontent.com/97767692/149597188-c734b15a-532b-4b6c-8999-c152616cb23d.png)

**Comment by ZroNoh** [comment]
This _may_ be intentional, but I could be wrong. You can find other end stone smelters inside The End for now.
