### ISSUE TITLE
[Mod Suggestion] Find Me

### ISSUE THREAD

**Issue by k3nw4y** [TeamAOF/All-of-Fabric-5#102]
[FindMe](https://www.curseforge.com/minecraft/mc-mods/findme) allows you to search for items in nearby inventories by pressing a key. For that you simply need to hover over an item

**Comment by KaneHart** [comment]
I use this myself and it works great. Keep in mind it is a server-side mod as well now.

**Comment by k3nw4y** [comment]
It currently has a bug with AE2 interface terminal, where it cant render the encoded recipe's output
https://github.com/Buuz135/FindMe/issues/20
![image](https://user-images.githubusercontent.com/46229190/150546083-858cf1a2-5b6e-4f73-a67a-c050463ecf72.png)

**Comment by k3nw4y** [comment]
its fixed in https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6132 , so it should be fine now
