### ISSUE TITLE
Efficiency Book

### ISSUE THREAD

**Issue by Random951753** [TeamAOF/All-of-Fabric-5#104]
Unable to use any Efficiency books on any tools.

**Comment by k3nw4y** [comment]
![image](https://user-images.githubusercontent.com/46229190/149812460-f2f65334-524e-44cd-8eae-5eaf2cc0b7fc.png)
also not available in Dark enchanter pack ver(0.2.11), EU server

**Comment by dillonwastaken** [comment]
Also unable to enchant with the /enchant command in my singleplayer world.
![image](https://user-images.githubusercontent.com/40649376/150117992-56226454-7554-49bb-8067-5828485504f5.png)

**Comment by Wielmo** [comment]
Also not possible with Botania's mana enchanter

**Comment by Glittersword** [comment]
Also I have found if you find efficiency on a book from a treasure chest it cannot be used.  I even tried removing one from an axe with an infusion table (which worked) but couldn't be used. The funny part was it wasn't the Efficiency Enchantment that I wanted.  I wanted the Curse that was on the axe so I could remove it with the Dark Enchantment Table for XP.  However the Efficiency seemed to be interfering with the process.
