### ISSUE TITLE
[Suggestion]Buff TR solars and other gens, buff IR gens and nerf Extra generators

### ISSUE THREAD

**Issue by k3nw4y** [TeamAOF/All-of-Fabric-5#106]
> So players explore other options instead of this

![image](https://user-images.githubusercontent.com/46229190/149792450-7f2cf5aa-8a8c-40b2-aa8e-fbfb104e54fe.png)

**Comment by yorii** [comment]
While on this topic, some rebalancing regarding the MFSU and the Lazuli Flux Container Mk4 should probably be considered:

LF Container Mk4:
Input/Output capacity: 16384/t
Storage capacity: 10 million

MFSU:
Input/Output capacity: 512/t
Storage capacity: 40 million

Add to this the fact that LF Container Mk4 is waaay easier to craft than the MFSU, the latter of which requires 12 platinum plates.

Additionally, the Mk3 container has 1 million storage and input/output of 4096/t, which even that is honestly better than the MFSU.
