### ISSUE TITLE
Lots of stuff broken in this pack.

### ISSUE THREAD

**Issue by SirTwsted** [TeamAOF/All-of-Fabric-5#108]
1. - I immediately started getting error codes when I started the pack for the first time.
>>> 
![Screenshot_118](https://user-images.githubusercontent.com/15247713/149875579-d830cf71-10de-4097-84cb-2b6aa54ce1ee.jpg)

2. - After restarting minecraft & even restarting computer.
Within 30 to 45 minutes within the game on the very first map, I started experiencing weird things.
Like when I mine, blocks just started to disappear even though I have the correct tool.

3. - Then whe I experienced not being able to mine any longer due to blocks just completely disappearing after trying to mine them,
I headed up stairs to my hideout (cubby-Hole) and tried to open a chest.  The chest would not open.
Then things just started to get more weird. 

Also note:  You guys forgot to add waypoints mod in this pack.
VERY important in minecraft.
Anyways,  I unInstalled the pack........
           I will wait a bit longer until things in this pack straighten out before trying again at a later time..
 
Cheers......

**Comment by ImAK9** [comment]
Use #support in our Discord server for further support on this https://discord.gg/6rkdm48
