### ISSUE TITLE
[Recomendation] packwiz

### ISSUE THREAD

**Issue by BabbyBlue** [TeamAOF/All-of-Fabric-5#11]
For people using multimc the curseforge implementation doesn't auto-update so packwiz would be a solution to that.

(also if this doesn't get added I understand because of permission and crediting the mod makers getting confusing with packwiz)

**Comment by Monster-Zer0** [comment]
we traditionally maintain a branch that uses packwiz. if you check aof4.. you should see that the latest is indeed packwiz.

however.. when a new pack is started, we have a need for rapid development.. it's easier (mostly for ak9) to have the main github branch be in the format it is now.

but.. rest assured.. when we get a stable modset.. have worked out all the compatibility and scripts.. Trent or I will be updating the main branch to be packwiz.
