### ISSUE TITLE
[Bug] Biomass generators are unable to heat up

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#110]
After a long discussion on the IndRev discord, I have come to the conclusion that the biomass generator in this pack isn't working the way it should.

Specifically it seems incapable of reaching the heated up stage where it produces 50% more power.

Even adding heating coils to it doesn't seem to do any difference, the temperature just goes back and forth but never reaches the point where the mod classifies it as heated up.

According to the mod authors, after it reaches about 1/3rd the way of the temperature bar, the tooltip should say "Heated up".
In AoF5, even at 2/3rds of the bar, it doesn't get heated up.

**Comment by dandin87** [comment]
The tooltip that says its heated up does not appear in the 1.18 version of IndRev, accoring to the actual dev NotSteven. This is not  pack issue. and the only config changes we make to IndRev are nerfing the solar gen, and disabling 3 of the ores that already generate from MI.

**Comment by yorii** [comment]
Yeah I noticed today that they did occasionally produce 96LF/t in my save, but it's highly irregular and doesn't stay that way for long, despite being constantly drained.

**Comment by yorii** [comment]
I'm not sure if I should maybe just report this bug directly to the IndRev github instead..?
