### ISSUE TITLE
[Missing Recipe] Tech Reborn Helium Bucket

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#115]
I can't find any way to craft TR Helium Buckets, which are required for 60k Helium Coolant Cell, which in turn are required for TR Superconductor, which is a requirement for all high tier tech reborn recipes such as the quantum armor set.

**Comment by k3nw4y** [comment]
You can use a TR tank,(empty cell+helium bucket gives helium cell)![image](https://user-images.githubusercontent.com/46229190/150059627-59e0184f-d8b9-4245-9412-5c45bdd1733d.png)

**Comment by yorii** [comment]
Aha thanks, I forgot helium cells are basically fancy buckets :-)
