### ISSUE TITLE
[Possible Oversight] Platinum Dust attainable with IndRev Mining Rig and TR Industrial Grinder.

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#119]
Hi, so basically I think you forgot to remove one of the alternative ways to getting Platinum Dust:

Chunk scan after Iridium vein (fairly common in taiga biome), run Iridium ore through Industrial Grinder with Mercury, yields you 1 Platinum Dust per Iridium Ore.
Still requires an EBF from MI to get ingots out of it.
Not sure if this is intentional or an oversight, but thought I should mention it anyway.

**Comment by yorii** [comment]
Related to this issue: https://github.com/GabrielOlvH/Industrial-Revolution/issues/373

**Comment by yorii** [comment]
A possible solution that at least removes the shortcut is to replace the 1 platinum dust output with 1 raw platinum, this at least forces you to process it like you would need with platinum from other sources.

**Comment by InFuRiTy** [comment]
Multiple ways of obtaining raw materials are fine if they are funneled down a linear gated path in order to actually use those materials later...maybe nerf the output of all of them to be in line with the MI way of getting them but don't disable them
