### ISSUE TITLE
No Bewitchment Salt (Solved)

### ISSUE THREAD

**Issue by CraftyCrafterBoi** [TeamAOF/All-of-Fabric-5#125]
There is no way I can find to get Bewitchment salt, which makes certain rituals impossible and makes it impossible to make salt lines on the floor to contain monsters and demons.  The only salt I can get is modern industrialization salt which does not seem to work for rituals nor can it be placed on the ground.

**Comment by ImAK9** [comment]
There is a shapeless conversion recipe for MI salt > BW salt.. Just put it anywhere in your crafting table.

**Comment by CraftyCrafterBoi** [comment]
Ohh I see. It didn't even show bewitchment salt in JEI, so I got confused. Thanks for the quick reply.
