### ISSUE TITLE
[Bug] Can You Trash It trashcans scramble your inventory and makes everything a ghost item until you move one

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#128]
Really freaky behaviour to be honest.
And is this mod really needed? There is already the Kibe trashcan and the MI Trashcan, not to mention the trash slot in your inventory.

**Comment by Monster-Zer0** [comment]
steps to reproduce?

**Comment by yorii** [comment]
1. have items in inventory
2. open trashcan
3. every item in your inventory gets misarranged
4. move any item and it all returns to normal
