### ISSUE TITLE
[Bug] Crashing on load due to error with a file not installing

### ISSUE THREAD

**Issue by sprwkd** [TeamAOF/All-of-Fabric-5#129]
Seems like a certain file is not being downloaded?

> java.lang.RuntimeException: Error creating Mixin config cloth-client-events-v0.mixins.json for mod cloth-client-events-v0
>     at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
>     at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
>     at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
>     at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config cloth-client-events-v0.mixins.json
>     at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
>     at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
>     at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
>     at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
>     ... 3 more
> Caused by: java.lang.IllegalArgumentException: The specified resource 'cloth-client-events-v0.mixins.json' was invalid or could not be read
>     at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
>     at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
>     ... 6 more

Exit code 0.

**Comment by Monster-Zer0** [comment]
looks like cloth config. dl latest or double check to make sure it didn't get dl'd twice.
