### ISSUE TITLE
[Mod Suggestion] Modular Loot Crates and Bundles

### ISSUE THREAD

**Issue by BinxetyBinx** [TeamAOF/All-of-Fabric-5#134]
https://www.curseforge.com/minecraft/mc-mods/fabric-loot-crates

Similar to Lootr for Forge. It would allow every player to explore the same dungeon/structure without losing out on loot.

**Comment by Monster-Zer0** [comment]
I second this. would help with multiplayer. as well as we can define the loot if need be.

**Comment by ImAK9** [comment]
working on adding this right now
