### ISSUE TITLE
[Meta suggestion] Add "AOF5" to the name of the modpack on CurseForge

### ISSUE THREAD

**Issue by SoulNylium** [TeamAOF/All-of-Fabric-5#137]
Every "All the Mods" pack has a part where it says "ATM#" in its name, which makes it so you can directly search, for example, "ATM7", and get one result in the search, which is the correct result. My proposition is to add "AOF#" to the modpack names in a similar style so you can simply type "AOF5" and get All of Fabric 5 as the only result. I will include image examples of how it works for ATM7 and how it works for AOF5 below.

ATM7 Example:
![ATM7 Example](https://user-images.githubusercontent.com/28793227/151677400-c8e42f58-0769-4ccc-a177-c64dab463016.png)

AOF5 Example:
![AOF5 Example](https://user-images.githubusercontent.com/28793227/151677478-52d887cd-928b-492c-acd1-c9029f867104.gif)

**Comment by Yoosk** [comment]
You can find all aof modpacks by searching `teamaof`

**Comment by SoulNylium** [comment]
Alright, guess it's not getting renamed then. I figured renaming it would have a positive effect but idk how CurseForge actually works with modpack renames.

**Comment by ImAK9** [comment]
done
