### ISSUE TITLE
Bees, ravens, owls, parrots can't fly

### ISSUE THREAD

**Issue by Ganoofib** [TeamAOF/All-of-Fabric-5#138]
all of the flying mounts are fine but all the little friendly mobs that should be able to fly and land can not fly at all, they cant even move up one whole block. had to make little stairs for bees to go up blocks, ravens can't even go up stairs. if you remove a block from under them they drop like a brick and get stuck in holes easily. it doesn't look like any one else put in an issue about this, so maybe i just messed something up, or maybe it got patched already in a newer version.
 I am using All of Fabric 5 version 0.2.5, and am using a bisect hosting server.

**Comment by yorii** [comment]
> All of Fabric 5 version 0.2.5

Could you perhaps try a newer version? 0.2.5 is like 6 updates old.
