### ISSUE TITLE
[Mod suggestion] Server side mods

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#139]
I noticed a clear lack of server-side utilities in the serverpack zip-file.
I understand that these shouldn't be included in the normal package, but shouldn't these be at least added to the serverpack?

Textile Backup:
https://www.curseforge.com/minecraft/mc-mods/textile-backup

Luckperms:
https://www.curseforge.com/minecraft/mc-mods/luckperms

Gunpowder with the teleport module for /home etc:
https://www.curseforge.com/minecraft/mc-mods/gunpowder-mc

Spark:
https://www.curseforge.com/minecraft/mc-mods/spark

Observable:
https://www.curseforge.com/minecraft/mc-mods/observable

**Comment by ImAK9** [comment]
These will be added to a second server zip, being worked on.
