### ISSUE TITLE
Modern Industrialization Destroing Tech reborn.

### ISSUE THREAD

**Issue by Splicee** [TeamAOF/All-of-Fabric-5#140]
Hi i would like to suggest a mods rebalance bacuse in Tech reborn for gears you have to use some forge hammers and rods and rings from modern industrialization. and one of the biggest problems for me is when i want to craft some kind of tech reborn late midgame or early endgame i have to go through whole modern industrialization because of  changed recipes from modern industrialization.

Please mage them separated there will be two iridiums and iridium plates and much other things but make them separated but interchangeable.

![image](https://user-images.githubusercontent.com/10261722/151762358-63c55544-42bb-4d6f-9ade-a9071553c7dc.png)
![image](https://user-images.githubusercontent.com/10261722/151762384-3ee7881c-5d86-4da0-840b-670ac5067cf1.png)
![image](https://user-images.githubusercontent.com/10261722/151762398-6daa9a17-0e39-4886-b06e-6160bf84a290.png)

**Comment by yorii** [comment]
haha no

**Comment by Azruine** [comment]
Well, those are intended afaik

so you have to do some MI stuff first :/
