### ISSUE TITLE
MI chromium / TR chrome integration?

### ISSUE THREAD

**Issue by Azruine** [TeamAOF/All-of-Fabric-5#141]
Afaik, the MI developers used the name chromium instead of chorme because of intended difference between MI and TR.

But this is modpack, and I think integrating those two chrome-variants is not bad.

Some recipes should be changed(e.g. electrolyzing 'cookable' chrome dust from ruby dust via TR) though.

**Comment by yorii** [comment]
Would be quite reasonably simple to do but requires a manual line in the kubejs unification script due to the spelling difference.
I can do an attempt at this later
