### ISSUE TITLE
[Recipe Suggestion] AE2 Presses Recipes

### ISSUE THREAD

**Issue by Demsli** [TeamAOF/All-of-Fabric-5#146]
So here`s the backstory. On a lonely night I have joined AOF5 Server and have noticed a little shop that sold 4 presses, each costing 1 iron block. Near was a sign that said something along the lines "Contact "Name" in case there are no presses left". So I thought to myself "Why bother someone when it is easier to make it yourself?". So I came up with the idea of press recipes. I did not want to make it too experty, so stuck to the basics. Every press needs a base - in my case, a cracked plate which is created on MI Forge:
![Cracked_plate](https://user-images.githubusercontent.com/53137074/152577207-07e9b891-764e-4926-87d6-2e480892bcd0.png)

It even has a little description on it:
![Plate_info](https://user-images.githubusercontent.com/53137074/152577274-381ec1b4-4017-49fb-9ab0-6a94dfb37c5a.png)

Then come the presses. Starting with Silicon:
![Silicon](https://user-images.githubusercontent.com/53137074/152577365-1a8cf0d5-5e74-4b8d-bf45-93b61d13acad.png)

Logic:
![Logic](https://user-images.githubusercontent.com/53137074/152577411-b20980ac-c289-4b42-85f8-f8b8c91425f4.png)

Engineering:
![Engineering](https://user-images.githubusercontent.com/53137074/152577441-fb70e33b-4ab7-4faa-8ffa-c4a123639ee6.png)

And finally - the Calculation:
![Calculation](https://user-images.githubusercontent.com/53137074/152577496-71ef9439-094b-484d-8ca5-26b0e98c2492.png)

I see how atrocious the cracked plate looks, not an artist really xD. Would like to hear the remarks and critique about the idea. I understand that some players like the feel of "exploring and finding presses", but it is a bit hard on a public server. So hope I kept a bit of original AE2 feel in these recipes. Thank you in advance for your feedback:)

P.S: The KubeJS code:

https://pastebin.com/KBcsW7r6 - press base code
https://pastebin.com/8Qd041uA - crafts of the presses
https://pastebin.com/2R0qj2pJ - press base description
https://pastebin.com/wyE3QJVq - adding the cracked plate to the game

**Comment by InFuRiTy** [comment]
Since the press plates have infinite uses once you obtain them and an ME system is fairly end-game I recommend changing the iron block with a harder to get material like a block of steel or netherite and also change the inscriber recipes to follow logic with that too.

**Comment by yorii** [comment]
> ME system is fairly end-game

🤔

**Comment by Yoosk** [comment]
Basic ME system you can get under hour starting fresh which is far from end-game.

**Comment by InFuRiTy** [comment]
> Basic ME system you can get under hour starting fresh which is far from end-game.

huh it didn't use to be that way....
maybe we should make it then if not end game at least mid-game
that way not everyone can spam autocrafters everywhere and poorly made networking setups, that can lag the servers to death, from their first hour joining into a new game!!
i also apologize this is getting off topic from this thread
feel free to ping me in discord foe further discussions on this

**Comment by yorii** [comment]
I don't know who fed you this infornation, but AE2 has always been a mod you can easily get into right from the start of the game. 
And any time it has caused lag issues have been due to an actual bug which was promptly fixed. 
This entire suggestion thread is in my honest opinion completely irrelevant, there are always more meteors to find (they are fairly common, and using the compass and /rtp command should make it easy to find all the plates even in an old server).
And there is absolutely no issue, balancewise, technically or otherwise, that would cause a problem with all the players building ME systems right from the start of the game.
Just my thoughts.

**Comment by Demsli** [comment]
> I don't know who fed you this infornation, but AE2 has always been a mod you can easily get into right from the start of the game. And any time it has caused lag issues have been due to an actual bug which was promptly fixed. This entire suggestion thread is in my honest opinion completely irrelevant, there are always more meteors to find (they are fairly common, and using the compass and /rtp command should make it easy to find all the plates even in an old server). And there is absolutely no issue, balancewise, technically or otherwise, that would cause a problem with all the players building ME systems right from the start of the game. Just my thoughts.

As can be seen - the recipes I have created don't really put AE into a midgame or endgame, you just need a MI Forge Hammer obtained within like an hour of game. As of your argument of infinite meteors - the world is limited, so you only have a number of them within world borders. Plus many times you need two meteors or even 3(when luck is bad). And number 3 - /rtp does affect server performance. Hence why there are always cool down. The Skript I have created is tps friendly and manages the hustle of "Hey does someone have this press? Will give you some cookies in return". And no, I am not an introvert, just was thinking of giving an alternative:)
