### ISSUE TITLE
The Resonating Enchantment from the Spectrum Mod is not picking up the Budding Amethyst.

### ISSUE THREAD

**Issue by Glittersword** [TeamAOF/All-of-Fabric-5#148]
It did in previous Versions of the Modpack. 
To be clear the Budding Cittrine and Topaz are still working properly.

**Comment by Sigler** [comment]
Can't get Topaz in mine with normal picks. Citrine and Amethyst work. 
Modern Industrialization drill can't feather touch budding Topaz blocks but CAN get the individual buds. Its currently the only way I can get Topaz to progress in Spectrum.
I haven't tried feather touch picks yet.

**Comment by Glittersword** [comment]
Use dark enchanter to get the Spectrum Enchantments on normal Picks. That will get the Budding Citrine and Topaz but isn't helping me with the Budding Amethyst.  It works fine with the Modded Geodes but not with the Vanilla one.
