### ISSUE TITLE
[Documentation] If unable to search for AOF5

### ISSUE THREAD

**Issue by WalnutFox** [TeamAOF/All-of-Fabric-5#15]
Unable to search for all of fabric 5 on multimc, FTB App, or curseforge.

Not sure what could be causing this but it doesnt show up in any app when searched 
example: [https://www.curseforge.com/minecraft/modpacks/search?search=all+of+fabric+5](https://www.curseforge.com/minecraft/modpacks/search?search=all+of+fabric+5)

**Currently Solution:**

- if you sort by recently updated and scroll though you will be able to find AOF5
- This solution currently only works with curseforge or multimc

![image](https://user-images.githubusercontent.com/6724171/145895662-81fe495f-6985-47ed-a426-0f7fbf1bc963.png)

**Comment by ImAK9** [comment]
Search "TeamAOF"

**Comment by WalnutFox** [comment]
Yes this does work but why cant we search All of Fabric 5, it works for 3 and 4...

**Comment by ImAK9** [comment]
This is on Curseforge to fix.
