### ISSUE TITLE
Game crashes when I got near a player

### ISSUE THREAD

**Issue by Actronix09** [TeamAOF/All-of-Fabric-5#157]
Im playing on a aternos server but everytime I got near my friend my game crashes, I couldnt check if it was only with a player entity but on single player evertthing seems okey.

I attach the crash report
[crash-2022-02-19_21.27.12-client.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/8110618/crash-2022-02-19_21.27.12-client.txt)
[crash-2022-02-19_21.43.49-client.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/8110619/crash-2022-02-19_21.43.49-client.txt)
[crash-2022-02-19_21.23.17-client.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/8110620/crash-2022-02-19_21.23.17-client.txt)
.

**Comment by Monster-Zer0** [comment]
hmm, this looks like possibly a megane issue? https://github.com/badasintended/megane

someone else may have to weigh in on it
