### ISSUE TITLE
Modern Industrialization destroying bewitchment

### ISSUE THREAD

**Issue by CheesyMarrow454** [TeamAOF/All-of-Fabric-5#158]
Because of Modern Industrialization i cant get the ores for Bewitchment i cant find silver(trust me i cant get it in creative or survival) and when i mine salt for bewitchment it turns into Modern Industrialization salt so i cant do A THING AND ITS FRUSTRATING!

**Comment by CheesyMarrow454** [comment]
And the only way to get salt from the bewitchment mod is from creative same with silver

**Comment by dandin87** [comment]
Incorrect. You use 2 MI salt stacked in the grid to make Bewitchment salt. MI silver works for all bewitchment recipes.

**Comment by CheesyMarrow454** [comment]
oh ok i still cant find silver though

**Comment by k3nw4y** [comment]
if you are playing on latest version the Industrial rev silver ores spawn on newly generated chunks
