### ISSUE TITLE
Support for Lithium?

### ISSUE THREAD

**Issue by desaianand1** [TeamAOF/All-of-Fabric-5#16]
At the moment, I don't believe Lithium is compatible, but are there plans to incorporate it down the line?

**Comment by Monster-Zer0** [comment]
please see previous packs.. all the way down to aof3 for ideas on what mods will most likely make it into the next update.

lithium.. has almost always been in the pack.

**Comment by desaianand1** [comment]
Lithium isn't in the latest AoF5 pack tho? Am I missing something here?

**Comment by desaianand1** [comment]
Or are you saying it will be added down the line as all the prev mods in Aof 4, 3 etc. once updated. At the moment, it conflicts with something and causes a startup crash, hence the question on compatibility.

**Comment by dandin87** [comment]
Lithium was in the pack. It was removed because it was crashing on 1.18.1. It just updated 8 hours ago and will be included in the next update.
https://www.curseforge.com/minecraft/mc-mods/lithium/files/3565566
