### ISSUE TITLE
Sorting a dank with multiple oversized stacks reduces one of the stacks to 64 items

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#160]
Figured I should post this here too, since I believe there is a config to blacklist the sorting of danks that could be applied to the servers as a workaround solution.

To reproduce:
Fill a dank with two stacks of the same item, where both stacks have more than 64 items.
Press the autosort button.
One stack will retain its original size, the other stack will be reduced to 64 items.

Issues posted to dank storage and inventory sorter githubs:
https://github.com/Tfarcenim/Dank-Storage/issues/158
https://github.com/kyrptonaught/Inventory-Sorter/issues/73

**Comment by kyrptonaught** [comment]
Does this sound like a feasible solution to help with this in the future?

https://github.com/kyrptonaught/Inventory-Sorter/issues/73#issuecomment-1057377527

**Comment by yorii** [comment]
> Does this sound like a feasible solution to help with this in the future?

Yeah that sounds like quite a good solution actually.
