### ISSUE TITLE
FTB Ultimine needs balancing

### ISSUE THREAD

**Issue by F1r3w477** [TeamAOF/All-of-Fabric-5#167]
In a vein miner type mod, you shouldn't be able to vein mine blocks using the wrong tool. (Ie: I shouldn't be able to vein mine stone with my fists) Sure, it doesn't give you the items, but that's a bit broken. I could just vein mine underground for diamonds and only use my fists. No material cost to go mining; just bring food. You won't even need to deal with the items filling your inventory. If this is paired with the Digging claws artifact, you can quickly dig through stone.

Not sure if the configs for FTB Ultimine allow for these changes, I personally preferred the vein miner mod from the previous modpack version, v0.2.11, it was less laggy and buggy.

**Comment by k3nw4y** [comment]
also diggus maximus has auto inventory insertion and also has shaped mining just like ultimine

**Comment by InFuRiTy** [comment]
FTB ultiminer offers more easily accessible vein mine options than DM also digging with your hand has double or even triple the penalty on your hunger which i find fair..

it could be configured to just destroy all of your hunger on vein-mining with your hand or the wrong tool as a punishment or just toggle the option to vein mine with correct tool only

don't get me wrong i really like DM too but Ultiminer offers the visual and info that DM doesn't..
if vein mine close to a lava ocean in the nether i wanna know if I'm about to make a deep dive in it or not...
