### ISSUE TITLE
Spectrum Mod Bug

### ISSUE THREAD

**Issue by Jade44789** [TeamAOF/All-of-Fabric-5#168]
Updated a server to the newest version of the Modpack but kept the old world. Now the Pigment Pedestals will not even start to craft recipes. It will acknowledge there is a valid recipe because it shows the item preview on top of the pedestal and the tricolor circle appears. Additionally, the guidebook is incomplete in areas that have been unlocked already.

I believe the issue is due to the reset of advancements on the server when updating the mod pack.

Any idea how to fix?

**Comment by dandin87** [comment]
I would first make a new pedestal. Not sure on the guidebook part

**Comment by k3nw4y** [comment]
also make sure you are powering the pedestal with a redstone signal
