### ISSUE TITLE
1.0.1 crashes when attempting to rearrange the servers in the Multiplayer menu

### ISSUE THREAD

**Issue by Justicetom21** [TeamAOF/All-of-Fabric-5#170]
Title. Completely fresh install, replicable by mousing over the servers in the menu and trying to click the up arrow that appears on the server icon. 

[crash-2022-03-04_18.40.37-client.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/8184335/crash-2022-03-04_18.40.37-client.txt)

**Comment by F1r3w477** [comment]
Did some testing on this, it only crashes if you try moving the bottom most server up in the list. This may be something to do with the recent change of adding [BisectHosting Server Integration Menu [FABRIC]](https://www.curseforge.com/minecraft/mc-mods/bisecthosting-server-integration-menu-fabric)

**Comment by F1r3w477** [comment]
Yeah, I removed BH Menu from the pack and it's no longer an issue. 

You can still join the servers without that mod, as it's only a client-side mod, that would be a temp fix if it bothers you.
