### ISSUE TITLE
[Bug] Iron Jetpacks Crash when using secondary visual only chest plate

### ISSUE THREAD

**Issue by hackrmomo** [TeamAOF/All-of-Fabric-5#173]
Game Crash when equipping Jetpack from Iron Jetpacks in `primary chest plate` slot and any secondary armor in `visual chest plate` slot:

![image](https://user-images.githubusercontent.com/5733032/156897555-27d5578a-ca68-42d3-a514-912d33227a02.png)

Details:

- AOF 5 Release v 1.0.0

**Comment by ImAK9** [comment]
this was fixed in 1.0.1
