### ISSUE TITLE
[bug] AIOTs disappear seemingly randomly

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#174]
As per the description, has happened to me 3 times now in a very short period of time.
Both a Diamond AIOT, and another persons Netherite AIOT seemingly at random just decide to vanish completely and without a trace.

No idea how to reproduce.

**Comment by yorii** [comment]
Another player in the server mentions it happened to them as well, around 4 times before the wipe on the previous version of the server.

**Comment by yorii** [comment]
I have managed to have this happen to me about 7 times now, but I still can't properly reproduce it on purpose.
And no, I am not accidentally breaking it, I suspected so as well for the first 3 times, but now it's very clear there is something else up, at one point it broke twice with only a few minutes in between, during which time I didn't even use the tool at all.

**Comment by ardaniel** [comment]
Anecdotally, I'm playing singleplayer, I got a diamond AIOT very early on from quest rewards, and it's reliably present so far (I've repaired it a couple times, etc.) If mine disappears I'll let you know what I was doing.

**Comment by InFuRiTy** [comment]
this happened to me also with my first AIOT and a couple of times with my MI iron hammers
they just disappeared out of nowhere
after that point my second AIOT is fully enchanted and netherited and still with me...for now
