### ISSUE TITLE
[Quests] MI quest for Stainless Steel/Digital Circuit in the wrong order

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#183]
![image](https://user-images.githubusercontent.com/7960287/157908671-db1776d8-7009-4090-8989-8b8c8e38497f.png)

Stainless Steel is a requirement to craft Digital Circuits, the proper order should go:
Vacuum Freezer -> Stainless Steel -> Digital Circuit

**Comment by yorii** [comment]
While on the topic, advanced upgrade should also be linked after distillery as that is a requirement for it.
![image](https://user-images.githubusercontent.com/7960287/157946952-7b90adca-eaf7-4190-ba7e-5f8673e21a06.png)

**Comment by yorii** [comment]
![image](https://user-images.githubusercontent.com/7960287/157948013-5fe52802-cfbb-4705-80a9-2396bac18138.png)
flexing epic paint skills

**Comment by yorii** [comment]
wait shit I made an error
![image](https://user-images.githubusercontent.com/7960287/157948117-fb39c44a-6b87-456e-8f21-ab5f03a1f5a1.png)

**Comment by yorii** [comment]
I just learned how to do this instead :)
![image](https://user-images.githubusercontent.com/7960287/157956065-e9f3ccfc-695a-48ce-a228-d56548b4ba57.png)

**Comment by yorii** [comment]
[modern_industrialization.zip](https://github.com/TeamAOF/All-of-Fabric-5/files/8235410/modern_industrialization.zip)

**Comment by yorii** [comment]
Someone said it looks messy, so here:
![2022-03-11_21 49 38](https://user-images.githubusercontent.com/7960287/157966456-bcb48e7b-b2bc-4916-bb86-60dede9f41a7.png)
[2022-03-11-21-47-36.zip](https://github.com/TeamAOF/All-of-Fabric-5/files/8235737/2022-03-11-21-47-36.zip)

**Comment by k3nw4y** [comment]
less messy one
![image](https://user-images.githubusercontent.com/46229190/157967949-21e70e04-0780-44b3-9f13-6c3e8574ed2c.png)
https://aofpaste.com/obazidapuc.snbt
