### ISSUE TITLE
[Modern Industrialization] Quest book Coke Oven recipe won't produce creosote as-is

### ISSUE THREAD

**Issue by ardaniel** [TeamAOF/All-of-Fabric-5#188]
The quest book's Coke Oven recipe in the Modern Industrialization section will not yield Creosote as-is because there's no fluid output hatch, which will block progress on getting a Lubricant Bucket to finish the Cutting Machine quest until that output hatch is added.

I'm not sure if this is intentional to prod players to do a little research outside of the quest book or not.

**Comment by johnneijzen** [comment]
![2022-03-15_23 19 31](https://user-images.githubusercontent.com/1343960/158411396-8dd56911-68f8-4faf-a41a-23b757193287.png)
like this way
