### ISSUE TITLE
Croptopia Pork Jerky Quest

### ISSUE THREAD

**Issue by DrMinotaur** [TeamAOF/All-of-Fabric-5#203]
The Croptopia 'Pork Jerky' item is not retrievable by my understanding, but it is a quest in the 'Agriculture' tab.
![image](https://user-images.githubusercontent.com/102099579/160011095-5900d7d0-b99d-49ab-b765-762e4ad3de0e.png)

**Comment by InFuRiTy** [comment]
Can confirm.

Both the pork and beef jerkies are unobtainable in game or the way/recipe for them doesn't show up in REI!!
