### ISSUE TITLE
Christmas Spirit: Tree looses decorations

### ISSUE THREAD

**Issue by Feuraver** [TeamAOF/All-of-Fabric-5#21]
After re-loading my game, the Christmas tree looses it's star and decorations.

**Comment by frqnny** [comment]
Close this, I will fix next update I know about Christmas Tree issues. just dont put diamond blocks on it allright?

**Comment by frqnny** [comment]
Close this, I will fix next update I know about Christmas Tree issues. just dont put diamond blocks on it allright?

**Comment by frqnny** [comment]
Close this, I will fix next update I know about Christmas Tree issues. just dont put diamond blocks on it allright?

**Comment by frqnny** [comment]
Close this, I will fix next update I know about Christmas Tree issues. just dont put diamond blocks on it allright?

**Comment by frqnny** [comment]
Close this, I will fix next update I know about Christmas Tree issues. just dont put diamond blocks on it allright?

**Comment by frqnny** [comment]
Close this, I will fix next update I know about Christmas Tree issues. just dont put diamond blocks on it allright?

**Comment by frqnny** [comment]
Close this, I will fix next update I know about Christmas Tree issues. just dont put diamond blocks on it allright?

**Comment by frqnny** [comment]
sorry im on phone which is broken
