### ISSUE TITLE
Add an expensive recipe for Dragon Eggs

### ISSUE THREAD

**Issue by Steelux8** [TeamAOF/All-of-Fabric-5#210]
From what I've heard people say in the EU server, there's only one egg to go around. There are uses for it, but no recipes to craft more than one, that I'm aware of. 

In servers, there is a necessity for more eggs when new people join and want to use one. Given that, I think this pack should have a recipe that people could use.

**Comment by InFuRiTy** [comment]
I second that!!!

**Comment by Modern-Bob** [comment]
Or at least have a new one spawn when a dragon is summoned and mauled.
