### ISSUE TITLE
GUI not functional in MacOS Catalina since 1.1.0

### ISSUE THREAD

**Issue by jjslocum3** [TeamAOF/All-of-Fabric-5#227]
When maximizing the default (small) startup menu window, the GUI doesn't scale. Instead the it maintains its dimensions, but is anchored at the lower left of the now maximized window. The graphical representations of the menu buttons don't match up with the hit-boxes for the buttons, so it's impossible to edit options, create a new game, etc.  This behavior also exists if you start a game from that startup menu, and then attempt to maximize the window after game load. This behavior didn't occur for me in the 1.0.0 and previous versions, nor in AoF 3 or 4.

Screenshot attached
<img width="1792" alt="Screen Shot 2022-04-02 at 12 00 16 AM" src="https://user-images.githubusercontent.com/9254206/161367092-431f47ae-49d1-4eca-ab5e-5ac20d316168.png">
.

**Comment by Sidaithe** [comment]
Temp fix for me was to remove the "better-loading-screen" mod from the mods folder. 

Hope it works for you.

**Comment by poppyseed0054** [comment]
I was having this issue also. My other instances worked though. Removed Better loading as recommended and it fixed it. Thank you!!
