### ISSUE TITLE
"Gate of Babylon" UI item

### ISSUE THREAD

**Issue by Modern-Bob** [TeamAOF/All-of-Fabric-5#230]
After we updated the server we run the modpack on, there is a UI item that appeared on the left side that says "Gate of Babylon 100%".
This started appearing after we updated to the modpack version 1.13
I attached a screenshot of the UI.

All the players on the server sees it and we cannot figure out how to remove it.
This does not appear if I start a new solo game with the modpack.

Look for all I could think of in the keybinds - no luck.
Google was of no help with the issue either :(

If anyone can assist, it would be greatly appreciated

![minecraft gate of babylon ui](https://user-images.githubusercontent.com/83513234/161888298-87cae202-4a59-422e-a0c6-28e7e72d7f5f.JPG)
.

**Comment by k3nw4y** [comment]
it's the FTB quests pinning the quest, check for the quest named that and unpin it from the quest window
