### ISSUE TITLE
High Memory Usage On Startup causing java heap crash

### ISSUE THREAD

**Issue by JensenButton9** [TeamAOF/All-of-Fabric-5#232]
The issue I'm having with AOF5 has me puzzled to exact cause of the issue as the error I get relates to a lack of memory but, allocating more memory to the server does not fix the issue but, rather prolongs the time until it runs out of memory and crashes. This issue started after I noticed  massive save lag spikes every 5 minutes along with the Danks saving this started at 3 second lag spikes at every 5-minute intervals on the 7th April but on the 8th of April today had increased to 16 second intervals so my intention was to fix this by reinstalling the mod and its associated files as this issue started out of the blue but, upon removing the mod the server refused to launch and produced the error that can be seen at the link below and re adding it did not fix it and using a backup prior to removing the mod did not fix it either. However, restoring to the backup of the save I did last night on the 7th Launches fine and only after its closed and re-launch does the memory error occur.  I'm not sure of the exact cause of the problem as apart from updating the pack is the only recent change apart from the world size hitting around 4 1/2 Gb was adding FTB ranks. Thankful not all is lost as I do make a habit of making a backup each day I put the server up but, until the cause can be found the error will likely re occur.

FYI:
I have added StorageCabinets, toms storage, c2me and ftbranks and removing theses mods did not fix the issue that I am experiencing and I ma running the latest version 1.1.4 and backporting to an older version did not fix the problem. Prior to this issue the server launch and worked fine with the 4Gb with the default server launch files.

Has anyone else experienced a similar issue?  Any ideas on the cause of this issue?

Update:
I have managed to open the world in single player after giving the client 14 GB of memory although it takes a long time to open the world. I tried this with the server, giving up to 16Gb to the server and it refused to launch but prior I got it to launch with 8Gb on the Xmx and 6Gb on the Xms. When I did get in I made use of spark and while running the server was using less than half of the allocated memory. Additionally the lag spikes just appear to be normal world save lag spikes, fixable.

Mapped Console Out: https://gist.github.com/JensenButton9/3ee05bc8d294c54f1ee6ff82016f0ddc

**Comment by ImAK9** [comment]
Remove Better Loading mod and try again.

**Comment by ImAK9** [comment]
Let me know the results of it

**Comment by JensenButton9** [comment]
> Let me know the results of it
Will do.

**Comment by JensenButton9** [comment]
> Let me know the results of it
It still crashes.

https://gist.github.com/JensenButton9/543cfa10300177344ddfe8bef3c74ee5

**Comment by dandin87** [comment]
Better loading screen doesn't load on the server anyways... so yeah. I see something about drink beer in here. was this a 0.2.x world updated? Looks like that would be correct. 

I believe another user found the issue was that the level.dat file keeps getting bigger and bigger because it keeps adding settings to the nether gen of the level.dat.

The only way to do this correctly, is to take a new world, copy the world gen settings for the nether and end from the level.dat, and replace the values of the old level.dat with these, you will want to make the seed match the old seed though. If you don't know how to NBT edit the files then that's the exact reason do not recommend updating pre 1.0 worlds.

Doing this fixed the issue for the other user.

**Comment by JensenButton9** [comment]
> 

Yes it was initially started in version 0.2.11. I will give this a try.

**Comment by JensenButton9** [comment]
> Better loading screen doesn't load on the server anyways... so yeah. I see something about drink beer in here. was this a 0.2.x world updated? Looks like that would be correct.
> 
> I believe another user found the issue was that the level.dat file keeps getting bigger and bigger because it keeps adding settings to the nether gen of the level.dat.
> 
> The only way to do this correctly, is to take a new world, copy the world gen settings for the nether and end from the level.dat, and replace the values of the old level.dat with these, you will want to make the seed match the old seed though. If you don't know how to NBT edit the files then that's the exact reason do not recommend updating pre 1.0 worlds.
> 
> Doing this fixed the issue for the other user.

Thank you, this fixed the issue, the error has disappeared, and the world is now playable again, this explains why it was getting harder to launch with each successive launch. This might explain if there was issue with terrain generation why the end dragon didn't spawn when me and my friend went to the end. Regardless, I have reset the end and nether as there was nothing built there by anyone.
