### ISSUE TITLE
Industrial Revolution recipe appearing with blank recipe

### ISSUE THREAD

**Issue by Paradox-Wolf** [TeamAOF/All-of-Fabric-5#24]
I am playing on a private home server. No files have been changed or modified. Playing on AOF version 0.2.3. 
I autofilled a recipe for a solar panel, I only had some of the materials, and with the incomplete craft it instead showed the result would be a lead AIOT. 

Recipe as viewed from Roughly Enough Items.
![image](https://user-images.githubusercontent.com/84997775/146617961-0112cfa8-1491-4b4e-b896-bbd204d19857.png)

An unrelated craft in an Applied Energistics Crafting Terminal showing its resulting craft as a Lead AIOT. 
![image](https://user-images.githubusercontent.com/84997775/146617971-cd273fbc-2af0-4a5b-a395-3e466a62ca89.png)

**Comment by ShockPuppet** [comment]
Happened today to me too, but it was the Tin AIOT

**Comment by ImAK9** [comment]
Fixed in 0.2.4
