### ISSUE TITLE
Can't Craft Lectern and BYG bookshelf

### ISSUE THREAD

**Issue by Magewings** [TeamAOF/All-of-Fabric-5#245]
Hello, I'm trying to make a emerald farm and when i got to the part of crafting lecterns i noticed i cant craft them. I'm using the BYG slabs and it wont let me craft a BYG bookshelf , it just craft the default vanilla one. 
![2022-04-17_17 50 02](https://user-images.githubusercontent.com/33807995/163733308-d2028ad6-01b6-4e33-843c-b517abb279ed.png)
any help would be helpful.

**Comment by Magewings** [comment]
update, i started out looking for other BYG trees, and i was able to craft the BYG bookshelf with a different type of BYG wood. so i guess its a bug that willow wood don't work.

**Comment by JensenButton9** [comment]
I made an emerald farm myself and found that the best way, considering villagers seem to be somewhat patched when it comes to how cheap you can make their trade using the zombie trick, was using the farmer villagers and more specifically, their pumpkin and melon trade after zombifying once.  The collection can be easily automated by using the Farmer from Industrial revolution. It should be noted though that trading with them multiple times a day for several days in a row without a break will eventually cause them to temporary raise prices although they will return to their reduced price after a few trade restocks.   


![2022-04-27_19 18 57](https://user-images.githubusercontent.com/49365963/165594543-7fc20b79-fc18-4eb6-bbe2-df2ca5ae87f1.png)
