### ISSUE TITLE
[Mod Suggestion] CC: Restitched

### ISSUE THREAD

**Issue by Just8Will** [TeamAOF/All-of-Fabric-5#248]
CC Restitched is available for 1.18.1
Since open computers isn't available any more it would be great to get some on aof5.

https://github.com/cc-tweaked/cc-restitched

**Comment by SirEdvin** [comment]
CC Restitched even available for 1.18.2 :)

**Comment by yorii** [comment]
Duplicate of #93 
And already added in dev branch for the 1.18.2 release

**Comment by SirEdvin** [comment]
:fireworks: :tada:

**Comment by dandin87** [comment]
Added in pack version 1.2.0
