### ISSUE TITLE
Negative value crashes

### ISSUE THREAD

**Issue by xxlio109** [TeamAOF/All-of-Fabric-5#250]
All of Fabric 5 - 1.1.5
All of Fabric 5 Server - 1.1.5
https://gist.github.com/xxlio109/1d1012e63004796c37045d7f3e815c43

**Comment by dandin87** [comment]
It was fixed in the 1.18.2 version and I backported the fix to the version in the pack. Remove the old IndRev file and use this one. Clients do not need to change anything.
https://cdn.discordapp.com/attachments/876545212900585533/963917743655108648/indrev-1.13.8-BETA-NegEnergyFix.jar
