### ISSUE TITLE
startserver.sh doesn't follow redirects when using curl

### ISSUE THREAD

**Issue by bvtthead** [TeamAOF/All-of-Fabric-5#253]
I was getting a corrupted  `serverstart-2.1.1.jar` since curl was just downloading 30X page returned by github. https://github.com/TeamAOF/All-of-Fabric-5/blob/79467426c8e419fdb853c8021c61f407b44d6780/server_files/startserver.sh#L30
`curl -LOJR "${URL}"` worked for me.

**Comment by lack** [comment]
I've fixed this before in #176, but then later changes reverted it :(
