### ISSUE TITLE
Nether not loading

### ISSUE THREAD

**Issue by JBar2K** [TeamAOF/All-of-Fabric-5#26]
When standing in a nether portal, the wiggly animation happens, but no nether. Tried deleting -1 dimension folder to regenerate the nether, but no change.

**Comment by RotatingBuffalo** [comment]
if i remember correctly, you need to crouch.

**Comment by dandin87** [comment]
> When standing in a nether portal, the wiggly animation happens, but no nether. Tried deleting -1 dimension folder to regenerate the nether, but no change.

And did you add any mods to the pack?

**Comment by JBar2000** [comment]
Crouching didn't work. 
No additional mods. 

The pack has been updated a few times before building portal. I'll do some experimenting. Was hoping for a known easy to fix bug. 

Thanx for the suggestions, I'll post my future findings.

**Comment by dandin87** [comment]
I know the fix. Its an old issue, and the mod preventing was removed because it needed updated after 1.18.1, but the only other occurrence I know of this, was someone who added extra dimensions to the pack. If you post you level.dat I can fix it, or if you copy the nbt data from a new single player world. The data to copy is under world gen, and you just copy the nether and end stuff . Replacing the seed value with the value from the overworld settings.

**Comment by JBar2K** [comment]
Thank you in advance.
Mind blown. I've never messed with NBT data before. Copied the Nether and End dimensions NPT data from a working world and pasted to the attached file. But I'm missing a step, maybe?, cuz when replacing the server file with the attached, the nether still did not open, just stood in the portal with swirliness around me. The nether did not generate. 

[level.zip](https://github.com/TeamAOF/All-of-Fabric-5/files/7772105/level.zip)

**Comment by dandin87** [comment]
Are you in our discord? Might be easier to figure this out. Do you still have the original level.dat file before you edited it? Only error I see here is that in the world gen settings I see an extra nether entry inside of the overworld settings that should not be there.

**Comment by JBar2K** [comment]
Thank you. You have shown me a lot. The World is not that important, so I'm resetting it. Updating to latest version of the pack the world would not even load. The small group of people using the server voted to start over so that we could use the latest pack now, cuz we are all at home on holiday. Timing is THE thing. Thanks so much.
