### ISSUE TITLE
AOF5 1.18.2 keeps crashing

### ISSUE THREAD

**Issue by KB-Q** [TeamAOF/All-of-Fabric-5#261]
I am able to play AOF5 after loading the world, but after a few minutes it crashes and closes the instance.

MultiMC log:
https://paste.ee/p/THpU6

Crash reports:
[crash-2022-05-08_19.39.10-client.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/8647126/crash-2022-05-08_19.39.10-client.txt)
[crash-2022-05-08_19.28.09-client.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/8647128/crash-2022-05-08_19.28.09-client.txt)

**Comment by yorii** [comment]
Remove your outdated JVM launch flags, half of those don't even do anything in Java 17.

**Comment by yorii** [comment]
And also increase the memory to the JVM, the pack will crash on 4GB that you have it set to.
