### ISSUE TITLE
"[STDOUT]: Saving player: false" spam in AOF5 1.2.0

### ISSUE THREAD

**Issue by johnneijzen** [TeamAOF/All-of-Fabric-5#263]
Cause by ThonkUtil 2.12.0+1.18 Fixed in next version

https://github.com/LimeAppleBoat/ThonkUtil/commit/016bfd285d5e148ed6c9a2be407fc9c7ebcb84fd

**Comment by dandin87** [comment]
That's great except the Thonk Util breaks a bunch of Enchant Registries in its next version....
