### ISSUE TITLE
[Mod Suggestion] UnlimitedPeripheralWorks

### ISSUE THREAD

**Issue by SirEdvin** [TeamAOF/All-of-Fabric-5#269]
Adds a bunch of new possibilities for Computers from CC:R,  shameless self promotion :) 

Most noticeable: 
- Provides support for fabric transfer api, so storages that don't implement `Container`, like ExtendedStorage chests are now usable
- Provides supports for fluid transfering
- Provides support for energy viewing inside energy storages

CurseForge: https://www.curseforge.com/minecraft/mc-mods/unlimitedperipheralworks
Documentation: https://docs.siredvin.site/unlimitedperipheralworks/

**Comment by dandin87** [comment]
Added in v1.2.1
