### ISSUE TITLE
Onyx Crafting from Spectrum

### ISSUE THREAD

**Issue by Shaaman221** [TeamAOF/All-of-Fabric-5#279]
The fusion pedestal does not craft onyx even though I fullfilled all the requirements.

**Comment by GSValore** [comment]
At the very least, on 1.2.0 it will work.  Just put in the ingredients right after midnight and leave them there.  It seems to be an issue with Spectrum that they don't start crafting until almost daybreak.  It should still be functional as of 1.2.2.
