### ISSUE TITLE
Massive amounts of Dumbo octopus spawning

### ISSUE THREAD

**Issue by generalm13** [TeamAOF/All-of-Fabric-5#284]
Not entire sure why this is happening but i DOUBT it's the meaning

=-=-=
EDIT 5?: (yes it's out of order, sue me :P) 
I've deduced it's more or less an issue caused by Goodall itself, but since AoF5 changes the mobspawn limits somehow it goes completely haywire with the Dumbo Octopus.
I've checked to see if it happens with any other animals but so far only the Octopus does this.
=-=-=

This seems to happen in both Singleplayer and Multiplayer (tested the same seed: -5945724250801399818)

And if the screenshots don't make it clear, those are almost ALL Dumbo Octopus

![octopus](https://user-images.githubusercontent.com/1728512/169645812-d275fc1f-b208-4c91-8479-62f168a8291c.png)

=-=-=
EDIT 1: Initial testing has learned me that they start to massively spawn the moment i go deeper underground (Y=-10?)
![2022-05-21_11 51 58](https://user-images.githubusercontent.com/1728512/169646116-2651b7db-5652-43e0-b3d9-9e0f3297e0b7.png)
=-=-=

=-=-=
EDIT 2: /kill @e[type=goodall:dumbo_octopus] results in numerous entity numbers (see added screenshot)
![kill](https://user-images.githubusercontent.com/1728512/169646518-ea4be393-ac33-4deb-b262-0ee35650c146.png)
=-=-=

=-=-=
EDIT 3: I tested other locations to see if it happens to other goodall mobs but it only seems to happen with the dumbo octopus, but it only seems to happen in areas where they can actually spawn. I tested a different part of the ocean i didn't see any of them spawn and the game was fine there.
![2022-05-21_12 17 14](https://user-images.githubusercontent.com/1728512/169647149-bc45ef77-4535-40ec-b8ff-cad2dc9bdb86.png)
=-=-=

Am now gonna see if it's purely the mod causing this or something else. Will report finding in a bit!

=-=-=
EDIT 4: With just FTB Ultimine, Chunks, Teams and Goodall in the pack the same thing happens but the amount of octopus is not so big the game starts to suffer.
![2022-05-21_12 28 43](https://user-images.githubusercontent.com/1728512/169647548-acbcadbc-d56c-4e8a-91ba-9609ab281d60.png)
=-=-=

**Comment by ImAK9** [comment]
Great reporting, thanks! Could you perhaps report this to the issue tracker of the mod?

**Comment by generalm13** [comment]
> Great reporting, thanks! Could you perhaps report this to the issue tracker of the mod?

already did, right after i posted it here

**Comment by generalm13** [comment]
> Great reporting, thanks! Could you perhaps report this to the issue tracker of the mod?

Modmaker asking what mod is adjust spawn rates: https://github.com/ThatGravyBoat/Goodall/issues/6

**Comment by dandin87** [comment]
Commented there. Nothing in the pack alters Spawn rates/Mob caps

**Comment by dandin87** [comment]
Fixed. Will be in the next pack update. until them anyone coming across this can download the updated version.
https://www.curseforge.com/minecraft/mc-mods/goodall/files/3800471
