### ISSUE TITLE
[Suggestion] Add Vein Mining

### ISSUE THREAD

**Issue by Pluettmann** [TeamAOF/All-of-Fabric-5#29]
Do you plan to add the Vein Mining mod? It is available since Dec 3rd for 1.18.1

**Comment by Yoosk** [comment]
Pretty sure aof5 got diggus maximus since like first release, and yes, thats vein mining mod.

**Comment by dandin87** [comment]
diggus maximus

**Comment by Devan-Kerman** [comment]
![cover5~2.jpg](https://user-images.githubusercontent.com/28693059/147370825-0259457b-c50f-4659-af4b-1affbf0aae23.jpg)
