### ISSUE TITLE
Some chunks are loading weirdly

### ISSUE THREAD

**Issue by bluee-js** [TeamAOF/All-of-Fabric-5#290]
When I joined the world and the chunks loaded, this happened:
![image](https://user-images.githubusercontent.com/64219777/170141461-ff2191f3-3b2f-4e68-879d-2a74bc83f56e.png)
And every time I reload the chunks there's a chunk like this.
![image](https://user-images.githubusercontent.com/64219777/170141513-76a78e07-165d-4227-a0c2-ebd2a3e66846.png)

**Comment by Monster-Zer0** [comment]
logs please.

also use a paste site.
you can use ours https://aofpaste.com

**Comment by bluee-js** [comment]
> logs please.
> 
> also use a paste site. you can use ours https://aofpaste.com

How can I get the logs?

**Comment by Monster-Zer0** [comment]
https://bfy.tw/T8A1
