### ISSUE TITLE
[Mod Suggestion] Vanilla Parts

### ISSUE THREAD

**Issue by Juuxel** [TeamAOF/All-of-Fabric-5#291]
[Vanilla Parts](https://www.curseforge.com/minecraft/mc-mods/vanilla-parts/) lets you place multiple slabs, torches, carpets, levers, buttons etc. into one block space (including mixed slabs of different materials!)

![](https://user-images.githubusercontent.com/6596629/170142659-ee6b0275-1f51-499d-bcad-44a498232f9c.png)

![](https://user-images.githubusercontent.com/6596629/170142704-c17e4241-cf99-45c0-a6c0-e9f377eb60b4.png)

(yes this is self-promo :wink:)

**Comment by Monster-Zer0** [comment]
ayyyy, I remember this mod.

pretty good pretty good.

We will most likely have to do some testing, but I don't see why we wouldn't approve it.
