### ISSUE TITLE
Golden Lasso "loses" stored mob

### ISSUE THREAD

**Issue by generalm13** [TeamAOF/All-of-Fabric-5#292]
I crafted 4 Golden Lasso's because i wanted to move a few Mooshrooms.
I put them in, but the moment i move them from my hotbar to my inventory, OFTEN the lasso "resets" and turns up empty
Scratch that, i didn't need to move them, half of my Golden Lasso's just bugs out and goes back to Empty after i put a mooshroom in. (If it makes a difference: this is my own server i host for a buddy, my wife and me.)

**Comment by JensenButton9** [comment]
I had the same issue when using multiple diamond lassos. The villagers kept disappearing, so I guess it wasn't my imagination then.

**Comment by generalm13** [comment]
> I had the same issue when using multiple diamond lassos. The villagers kept disappearing, so I guess it wasn't my imagination then.

I figured out it's mostly a visual Glitch, the mob goes invisible but is still there.
The moment you relog they re-appear.
