### ISSUE TITLE
Advancement is gone

### ISSUE THREAD

**Issue by Penaiel** [TeamAOF/All-of-Fabric-5#298]
I am playing AOF 5 - 1.2.3.

Advancement screen is empty, both on FTB and Curseforge, tried them both.

And mod pack includes Advancement plaques and Advancement Enlarger so I figured advancements should be included.

![2022-05-28_12 08 12](https://user-images.githubusercontent.com/90971470/170820822-93512031-c92a-4655-9f63-601975ba834e.png)
6

**Comment by drharlow** [comment]
I am experiencing the same problem! 
![2022-05-29_19 04 36](https://user-images.githubusercontent.com/4072056/170894938-e9f70e43-acfa-4496-a841-1e6e60814a0f.png)
![2022-05-29_19 04 48](https://user-images.githubusercontent.com/4072056/170894939-74d4102d-cd3d-4c45-a017-c5152e399417.png)
![2022-05-29_19 04 55](https://user-images.githubusercontent.com/4072056/170894940-f0c0420d-5ad4-458d-b771-ff6856315ec6.png)
![2022-05-29_19 05 05](https://user-images.githubusercontent.com/4072056/170894941-d9305d5a-9460-488a-b352-8601fb77fe37.png)

**Comment by ImAK9** [comment]
Fixed in 1.2.4
