### ISSUE TITLE
Allow recipes for same machines across mods

### ISSUE THREAD

**Issue by tdgPLS** [TeamAOF/All-of-Fabric-5#312]
Hi,

I'm going through the Tech Reborn quest line in AoF 5 1.2.3 and trying to craft the iridium alloy plate recipe but going through it, it seems to requires the Modern Industrialization EBF instead of the already crafted Tech Reborn blast furnace for stainless steel.
Also the same with the implosion compressor when trying to make the blastproof alloy ingot, need the Modern Industrialization one and cannot use the Tech Reborn implosion compressor.

Thanks!

**Comment by mguidry-glodon** [comment]
Yes iridium plate needs blastproof alloy which is requiring stainless steel which requires you to progress all they way to modern industrialization vacuum freezer to get stainless steel from stainless steel hot.

**Comment by tdgPLS** [comment]
Sure, but the point of the original issue was to ask if the same machines (Tech Reborn Blast Furnace and MI Blast Furnace for example) can be used for the same recipe, e.g. the iridium alloy plate recipe.
