### ISSUE TITLE
No Enchanted Books in REI

### ISSUE THREAD

**Issue by unilock** [TeamAOF/All-of-Fabric-5#315]
In REI, when searching for any particular enchantment (e.g. "Sharpness"), I'd expect to see the Enchanted Book(s) for that enchantment ("Sharpness I, II, III"). I'd also expect to see every Enchanted Book with an enchantment when searching for "Enchanted Book".

Instead, I see only one Enchanted Book - the generic one (no enchantment associated, shown in recipes in REI).

This issues doesn't exist with only REI installed.

Actual:
![image](https://user-images.githubusercontent.com/11802133/171459293-21385951-4a05-48e5-85f4-0b356bff9530.png)

Expected:
![image](https://user-images.githubusercontent.com/11802133/171458590-af7c27e0-2c88-4dd7-8008-76a95938e559.png)

**Comment by dandin87** [comment]
This is not an REI bug (btw, there is a fabric version of JEI now, but we will not use it), but rather a pack bug. A mod in the pack is preventing them from showing up. We are unsure which mod is causing this. I have done some testing by removing the main mods that add enchants, but it was not any of them. So only way to figure it out is disabling mods and trying it, which takes a lot of time. So just haven't got around to it. You can view enchant books from the creative menu in the meantime

**Comment by unilock** [comment]
@trevorjd Oops, yes, I meant REI.

I can try going through the mods to find the one at fault. My guess is KubeJS, as that's the reason Spectrum's "Enchanter" can't upgrade enchanted books (from one level to the next). Obviously, though, that's not a mod that can be removed...

**Comment by dandin87** [comment]
Mods that are not Causing the issue.
Kubejs
Spectrum
Incantationem
Wmitaf - adds the mod name to the enchant desc, instead of all being labeled "minecraft"
EnchantmentDescriptions
Enchancement
Biome Makeover

**Comment by unilock** [comment]
The mod at fault is [Egg Tab](https://www.curseforge.com/minecraft/mc-mods/eggtab-fabric). Updating [REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) and its dependencies ([Architectury API](https://www.curseforge.com/minecraft/mc-mods/architectury-api), [bad packets](https://www.curseforge.com/minecraft/mc-mods/badpackets), [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api)) did not solve the issue.

**Comment by unilock** [comment]
Updating to Fabric v0.14.7 doesn't help either.
Nor does disabling the "Enchanted Books" tab Egg Tab adds to the Creative mode interface via the following in `/config/eggtab.toml`:
```
booksGroup = false
```

**Comment by dandin87** [comment]
Thanks! I was going to check the mod that adds a creative tab of books, but forgot the name of it. Making an issue on the mods page and pinged them in our dev channel.

**Comment by dandin87** [comment]
And EggTab has an update fixing this now. Will be included in the next pack update.

**Comment by unilock** [comment]
Fixed as of v1.3.0.
