### ISSUE TITLE
[Crash] Game crashed when skeleton kills zombie

### ISSUE THREAD

**Issue by Kinsogu** [TeamAOF/All-of-Fabric-5#318]
My game crashes when Skeleton killed zombie by bow.

Curse Forge Launcher, All of Fabric 5 - 1.2.4, Java 17.0.2, Win10, i7 6700HQ, GTX 1060

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 6/2/22, 12:52 AM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1792.method_40131()" because the return value of "net.minecraft.class_1799.method_7909()" is null
	at net.minecraft.class_1799.method_31573(class_1799.java:230)
	at vazkii.botania.client.gui.HUDHandler.onDrawScreenPost(HUDHandler.java:181)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$efh000$render(class_329.java:8529)
	at net.minecraft.class_329.method_1753(class_329.java:415)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1799.method_31573(class_1799.java:230)
	at vazkii.botania.client.gui.HUDHandler.onDrawScreenPost(HUDHandler.java:181)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$efh000$render(class_329.java:8529)
	at net.minecraft.class_329.method_1753(class_329.java:415)

-- Affected level --
Details:
	All players: 1 total; [class_746['Kinsogu'/261, l='ClientLevel', x=-277.33, y=70.00, z=125.24]]
	Chunk stats: 4096, 1830
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,88,0), Section: (at 0,8,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 14824 game time, 14824 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1330588232 bytes (1268 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c60
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18771.92
	Virtual memory used (MB): 15307.98
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 39.22
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 4.0.4
		adorn: Adorn 3.5.0+1.18.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
		advancementplaques: Advancement Plaques 1.4.4
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.10
		ae2: Applied Energistics 2 11.0.0
		ae2things: AE2Things 1.1.0-beta.6
		ae2wtlib: AE2WTLib 11.0.1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.2
		aofemotes: AOF Emotes 0.0.4
		appbot: Applied Botanics 1.2.1
		appleskin: AppleSkin 2.4.0+mc1.18.2
		aqupdcaracal: Caracal mob 1.18.2-1.3.8
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		arcanus: Arcanus 1.29
		architects_palette: Architect's Palette Fabric 1.7
		architectury: Architectury 4.4.68
		artifacts: Artifacts 7.0.3+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 14.0.2
		authme: Auth Me 3.1.0
		auto-workstations: Auto Workstations 1.0-SNAPSHOT-9
		autoconfig1u: Auto Config v1 Updated 3.4.0
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 3.0.0+0
		basicaiots: Basic AIOTs 1.3.3+1.18.2
		bcc: BetterCompatibilityChecker fabric-1.0.5
		beaconoverhaul: Beacon Overhaul 1.6.0+1.18.2
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		better_bad_omen: Better Bad Omen 1.2.0
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.1.3
		bettermounthud: Better Mount HUD 1.1.4
		betterpingdisplay: Better Ping Display 1.1.1
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		bewitchment: Bewitchment 1.18-20
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			impersonate: Impersonate 2.4.1
			playerabilitylib: Pal 1.5.0
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		bhmenu: BHMenu-Fabric 1.17.1-1.18.2-1.3
		biomemakeover: Biome Makeover 1.18.2-1.4.23
		bitsandchisels: BitsAndChisels 2.6.8
			stacc: Stacc 1.2.3
		blast: BLAST 1.9.1
		blockus: Blockus 2.4.7+1.18.2
		bookshelf: Bookshelf 13.1.16
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.7-1.18.2
			maelstrom_library: Maelstrom Library 1.2.4-1.18.2
			multipart_entities: MultipartEntities 1.1.5-1.18.2
		botania: Botania 1.18.2-432-FABRIC
			fiber: fiber 0.23.0-2
		bowinfinityfix: Bow Infinity Fix rv11
		breakprogress: Break Progress 1.0.1
		buildinggadgets: st'ructure tools 1.0.21
			mm: Manningham Mills 2.3
		builtinservers: Builtin Servers 1.0.1-BETA+1.18
		byg: Oh The Biomes You'll Go 1.4
		cacao: Croptopia's Chocolaterie 1.1
		campanion: Campanion 3.0.3
		camsbackpacks: Cammie's Wearable Backpacks 2.11
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.2.0
		capybara: Capybara 1.0.4
		cardinal-components: Cardinal Components API 4.1.4
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-chunk: Cardinal Components API (chunks) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
			cardinal-components-level: Cardinal Components API (world saves) 4.1.4
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.4
			cardinal-components-world: Cardinal Components API (worlds) 4.1.4
		carrier: Carrier 1.10.0
		catwalksinc: Catwalks Inc. 1.3.0
		chalk: Chalk 2.0.1+1.18.2
		charm: Charm 4.1.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmonium: Charmonium 4.0.0
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chimes: Chimes 1.1.1
		chisel: Chisel Refabricated 1.4.5
		cleancut: CleanCut 1.18-4.0-fabric
		clienttweaks: Client Tweaks 7.1.0
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+8
		companion: Companion 2.0.1
		computercraft: CC: Restitched 1.100.6
		conjuring: Conjuring 1.0.22+1.18
		continuity: Continuity 1.1.0+1.18.2
		controlling: Controlling For Fabric 9.0+19
		couplings: Couplings 1.8.0+1.18.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		coxinhautilities: Coxinha Utilities 1.3+1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
			omega-config-gui: Omega Config GUI 1.2.3-1.18.1
				cloth-config-lite: cloth-config-lite 2.0.6
			team_reborn_energy: Energy 2.2.0
		craftingtweaks: Crafting Tweaks 13.0.0
		crawl: Crawl 0.10.6
		create: Create mc1.18.2_v0.4.1+586
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 1.18-0.6.2.25
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			noindium: No Indium? 1.0.1+1.18.2
			porting_lib: Porting Lib 1.1.0-beta+1.18.2-dev.ffa2ca8
				com_github_llamalad7_mixinextras: MixinExtras 0.0.9
			registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
				fabric-data-generation-api-v1: Fabric Data Generation API (v1) 2.0.9+e19de87d60
		createplus: CreatePlus 1.0
		creeperoverhaul: Creeper Overhaul 1.3.1
		croptopia: Croptopia 2.0.3
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		croptosis: Croptosis 1.5.0
		cyti: Can You Trash It? 1.0.5
		dankstorage: Dank Storage 1.18.2-3.7
		dark-enchanting: Dark Enchanting 1.0.0+1.18.2
			libgui: LibGui 5.4.0+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
				libninepatch: LibNinePatch 1.1.0
		darkpaintings: DarkPaintings 10.0.3
		darkutils: DarkUtilities 10.0.4
		dawn: Dawn API 3.3.1
		deathlog: DeathLog 0.2.9+1.18
		decorative_blocks: Decorative Blocks 2.1.0
		deepslatecutting: Deepslate Cutting 1.3.4
			maybe-data: Maybe data 1.3.1-1.18.2
		defaultoptions: Default Options 14.1.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		display_case: Display Case Mod 1.0.0
		dml-refabricated: Deep Mob Learning: Refabricated 1.18.2
			dml-refabricated-base: DML: Refabricated - Base 1.18.2
			dml-refabricated-events: DML: Refabricated - Vanilla Events 1.18.2
			dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 1.18.2
			dml-refabricated-rei: DML: Refabricated - REI Integration 1.18.2
			ktdatataglib: KtDataTagLib 1.6.5+1.18.2
		dmlsimulacrum: Deep Mob Learning: Simulacrum 0.5.4-beta
		dragonloot: DragonLoot 1.0.10
		dual_riders: Dual Riders 1.1.1
		duckling: Duckling 1.0.5
		dusk: Dusk Mod 1.18.2-1.9
		dustrial_decor: Dustrial Decor 0.5
		dwarfcoal: Dwarf Coal 1.18.1-1.0.1
		dyed: Dyed 1.0.2
		dynamicfps: Dynamic FPS 2.1.0
		ecologics: Ecologics 1.5.4
		eggtab: Egg Tab 2.2.0+1.18-fabric
		ellemes_container_lib: Ellemes' Container Library 1.4.0-beta.1
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchancement: Enchancement 1.18-17
		enchdesc: EnchantmentDescriptions 10.0.3
		entitybanners: Entity Banners 1.0.2-BETA+1.18
			bannerpp: Banner++ 2.0.4+mc.1.18-rc4
		equipmentcompare: Equipment Compare 1.2.12
		expandedstorage: Expanded Storage 7.4.0-beta.2
		experiencebugfix: Experience Bug Fix 18
		extraalchemy: Extra Alchemy 1.8.1
		extragenerators: Extra Generators 1.2.1-BETA+1.18
		extremesoundmuffler: Extreme sound muffler 3.26_fabric-1.18.1
		fabric: Fabric API 0.53.4+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.1+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.5+d82b939260
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.16+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.0+85719ab760
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.12+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.4+d8d7804a60
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.1+81ea5b3c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
			fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.1+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.0+2afceb2960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.2+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		fabricloader: Fabric Loader 0.14.6
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		farmingforblockheads: Farming for Blockheads 10.0.0
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		findme: FindMe 3.0.6
		floral_flair: Floral Flair 1.3.0
		flytre_lib: FlytreLib 1.8.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		ftbchunks: FTB Chunks 1802.3.6-build.145
		ftblibrary: FTB Library 1802.3.6-build.119
		ftbquests: FTB Quests 1802.3.8-build.101
		ftbteams: FTB Teams 1802.2.6-build.51
		ftbultimine: FTB Ultimine 1802.3.3-build.55
		gateofbabylon: Gate Of Babylon 1.7.0-1.18.2
		geckolib3: Geckolib 3.0.42
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.2
		glassential: Glassential 1.3.0
		go-fish: Go Fish 1.5.0-1.18.2
		goblintraders: Goblin Traders 1.5.1
		goldenhoppers: Golden Hoppers 1.3.0
		goodall: Goodall 1.0.2
		graveyard: The Graveyard 1.8
		graveyard_biomes: The Graveyard Biomes 1.1
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.14
		guild: Guild 0.4.0
		harvest_scythes: Harvest Scythes 2.5.0
		healthoverlay: Health Overlay 6.0.1
		horseinfo: Horse Info 0.4.1-1.18
		iceberg: Iceberg 1.0.38
		iknowwhatimdoing: I Know What I'm Doing 4.0.0
		impaled: Impaled 1.1.3
		improved-stations: Improved Stations 2.1.0
		incantationem: Incantationem 1.1.3+1.18.2
		indium: Indium 1.0.3+mc1.18.2
		indrev: Industrial Revolution 1.14.0-BETA
			libblockattributes_core: LibBlockAttributes (Core) 0.10.0
			libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
			libblockattributes_items: LibBlockAttributes (Items) 0.10.0
			magna: Magna 1.7.0-1.18-pre1
		infusion_table: Infusion Table 1.0.5
		inmis: Inmis 2.6.0-1.18.2
		inventoryhud: Inventory HUD + 3.4.2
		inventorysorter: Inventory Sorter 1.8.6-1.18
			kyrptconfig: Kyrpt Config 1.4.2-1.18
				blue_endless_jankson: jankson 1.2.1
		iris: Iris 1.2.4-build.38
			org_anarres_jcpp: jcpp 1.4.14
		iron-jetpacks: Iron Jetpacks 0.4.3
		itemfilters: Item Filters 1802.2.7-build.21
		jamlib: JamLib 0.0.5
		java: OpenJDK 64-Bit Server VM 17
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kibe: Kibe 1.9.7-BETA+1.18
		kjsextras: KubeJS Extras 3.0.0
		kleeslabs: KleeSlabs 11.0.0
		kubejs: KubeJS 1802.5.3-build.463
		kubejs_create: KubeJS Create 1802.2.2-build.23
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.4
		lifts: Lifts 1.4.1-BETA+1.18
		lightoverlay: Light Overlay 6.0.5
		lithium: Lithium 0.7.10
		logprot: Logprot Mod 1.18-1.6
		lootr: Lootr 0.3.20.57
		lovely_snails: Lovely Snails 1.0.4+1.18
		magicalforest: Magical Forest 2.0.2
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.4
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwpaintings: Macaw's Paintings 1.0.3
		mcwroofs: Macaw's Roofs 2.1.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.5
		mcwwindows: Macaw's Windows 2.0.3
		megane: megane 7.5.1
			megane-api: megane-api 7.1.0
			megane-applied-energistics-2: megane-applied-energistics-2 7.1.0
			megane-deep-mob-learning-simulacrum: megane-deep-mob-learning-simulacrum 7.1.0
			megane-extra-generators: megane-extra-generators 7.1.0
			megane-fabric-transfer: megane-fabric-transfer 7.1.0
			megane-industrial-revolution: megane-industrial-revolution 7.1.0
			megane-kibe: megane-kibe 7.1.0
			megane-lib-block-attributes: megane-lib-block-attributes 7.1.0
			megane-reborn-core: megane-reborn-core 7.1.0
			megane-reborn-energy: megane-reborn-energy 7.0.0
			megane-runtime: megane-runtime 7.2.0
			megane-tech-reborn: megane-tech-reborn 7.1.0
			megane-vanilla: megane-vanilla 7.1.1
			megane-wireless-networks: megane-wireless-networks 7.1.0
		minecarttweaks: Cammie's Minecart Tweaks 1.5
		minecraft: Minecraft 1.18.2
		mobscarecrow: Mob Scarecrow 1.2.2
		mocolors: Mo' Colors 1.4.0
		modern_industrialization: Modern Industrialization 1.1.1
		moderndynamics: Modern Dynamics 0.2.1-beta
		modmenu: Mod Menu 3.2.2
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		mostructures: Mo' Structures 1.4.2+1.18.2
		mousetweaks: Mouse Tweaks 2.22
		mtmechs: Magitek Mechs 1.0.12
		mythicmounts: Mythic Mounts 1.18.2-7.0
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nears: Nears 1.1.8
		netherportalfix: NetherPortalFix 9.0.0
		no_angled_brackets: No Angled Brackets 1.0.0
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		onastick: On A Stick 2.0.0
		openloader: OpenLoader 12.0.1
		overloadedarmorbar: Overloaded Armor Bar 1.18.1-6
			gbfabrictools: GBfabrictools 1.2.2+1.16
		owo: oωo 0.7.2+1.18
		paginatedadvancements: Paginated Advancements 1.0.0
		patchouli: Patchouli 1.18.2-69-FABRIC
		pehkui: Pehkui 3.3.2+1.14.4-1.19
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		peripheralium: Peripheralium 0.1.1
		peripheralworks: Unlimited Peripheral Works 0.1.2
		phosphor: Phosphor 0.8.1
		pigpen: PigPen 8.0.1
		pling: Pling 1.5.0
		plushies: Plushie Mod 1.2
		probablychests: Probably Chests 0.4.3
		promenade: Promenade 2.6.3
			terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		pyrotastic: Pyrotastic 1.18.2+0.0.2
		questsadditions: Quests Additions 1.3.1
		quickshulker: Quick Shulker 1.3.6-1.18
			shulkerutils: shulkerutils 1.0.4-1.18
		raised: Raised 1.1.1
		rare-ice: Rare Ice 0.4.1
		reborncore: Reborn Core 5.2.0
		redstonebits: Redstone Bits 1.8.2
		replanter: Replanter 1.3
		repurposed_structures: Repurposed Structures 4.1.10+1.18.2
		respawnablepets: Respawnable Pets 1.18-4
		rhino: Rhino 1802.1.13-build.175
		rightclickharvest: Right Click Harvest 2.0.6
		roughlyenoughitems: Roughly Enough Items 8.2.470
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		runelic: Runelic 11.0.1
		secretrooms: Secret Rooms 1.3.1+1.18.2
		shulkerboxtooltip: Shulker Box Tooltip 3.0.8+1.18.2
		simpleteleporters: Simple Teleporters 2.3.0
		simplevoidworld: Simple Void World 4.0.0
		slight-gui-modifications: 'Slight' GUI Modifications 2.1.0
			org_codehaus_groovy_groovy: groovy 3.0.8
			org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		slimyfloor: Slimy Floor 1.18-1.2.2
		slotlock: SlotLock 1.0.4-BETA+1.18
		smootherbedrock: Smoother Bedrock 1.0.4
		smwyg: Show Me What You Got 1.0.1
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		someforgepatchesported: Some Forge Patches Ported 1.0.3
		spark: spark 1.9.1
		spectrum: Spectrum 1.3.3-1.18.2-midgame18-trinkets-brewing
			additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
		staffofbuilding: Staff of Building 1.4.1-1.18.1
		stoneholm: Stoneholm 1.4.3
		strawdummy: Straw Dummy 1.7.0
		techreborn: Tech Reborn 5.2.0
		terrablender: TerraBlender 1.1.0.101
		terrarianslimes: Terrarian Slimes 1.2-BETA+1.18
		thatched: Thatched 1.1.0
		thonkutil: ThonkUtil 2.14.1+1.18
			thonkutil-base: ThonkUtil Base 1.12.2+23c1dc2c60
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.2+9e23427060
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.19+9b80223760
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.14+9b80223760
			thonkutil-legacy: ThonkUtil Legacy 1.0.20+9b80223760
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.12+9b80223760
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.1+9b80223760
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.1.9+9b80223760
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.20+9b80223760
		timeoutout: TimeOut Out 1.0.1+1.18
		toolstats: ToolStats 9.0.3
		tooltipfix: ToolTip Fix 1.0.4-1.18
		totemmod: Wither Totems Mod 0.3.5-1.18.2-pre2
		totw_additions: Towers of the Wild: Additions 1.2.1
		transportables: Transportables 1.2
		trapexpansion: Trap Expansion 1.3.3
		trashslot: TrashSlot 11.0.2
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.3.1
		twigs: Twigs 1.1.3-patch1+1.18.2
		updatefixerupper: UpdateFixerUpper 1.0.0
		vanilla-hammers: Vanilla Hammers 3.4.0-1.18.2
			static-content: Static Content 1.0.2-1.16.2
				staticdata: Static Data 1.1.2
		vanillaexcavators: Vanilla Excavators 1.1.0
		villager-hats: Villager Hats 1.4.0
		visuality: Visuality 0.4.2
			goosik-config: goosik-config 0.2.0
			tlcosmetica: Cosmetica 0.4.0
		voidtotem: VoidTotem (Fabric) 1.18.2-1.3.1
		waystones: Waystones 2.5.3
		wirelessnetworks: Wireless Networks 1.5.1
		wmitaf: WMITAF 2.2.0
		wolveswitharmor: Wolves With Armor 1.7.1-1.18.2
		wthit: wthit 4.10.3
		xlpackets: XLPackets 2.1-1.17.1
		xps: Xp Obelisk 0.3.9.r_for_1.18.x_Fabric
		yigd: You're in Grave Danger 1.3.6
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
	Loaded Shaderpack: (off) [fallback, check your logs for errors]
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.6-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.79, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Kinsogu'/261, l='ServerLevel[Kinsogu]', x=-277.33, y=70.00, z=125.24]]
	Data Packs: vanilla, minecraft/croptop, createplus/createplus-core, Fabric Mods
	World Generation: Stable

**Comment by atreydesai** [comment]
I also have the same issue.
