### ISSUE TITLE
Chisel Enhancement

### ISSUE THREAD

**Issue by Nekohime1989** [TeamAOF/All-of-Fabric-5#320]
There's a ton of different new blocks not supported by chisel and variants of vanilla blocks not supported by chisel.
And I was thinking perhaps it would be nice if that was made possible.

**Comment by szumaster** [comment]
It probably doesn't depend on the modpack creators, but on the developer of the modification. Anyway, you'll have to wait, this idea has already been mentioned [here](https://github.com/matthewperiut/Chisel-Fabric/issues/9#issue-1098595518).
