### ISSUE TITLE
Unable to power Modern Industrialization with anything but itself (AoF 1.2.3)

### ISSUE THREAD

**Issue by tdgPLS** [TeamAOF/All-of-Fabric-5#321]
As the title says, am unable to power Modern Industrialization machines such as the electric blast furnace with anything other than power generation from Modern Industrialization.

**Comment by OweningIt** [comment]
That's not a bug. MI uses a separate power system for balance and progression reasons.

**Comment by tdgPLS** [comment]
Ah fair enough, my mistake. The official MI curseforge page says "Modern Industrialization is also compatible with your favourite Fabric Tech Mods such as AE2, Tech Reborn or Industrial Revolution", I guess I misunderstood.

**Comment by OweningIt** [comment]
That means that you can power other mods machines with mi generators, not the other way around
