### ISSUE TITLE
KubeJS map receiver problem

### ISSUE THREAD

**Issue by B7Kompirine** [TeamAOF/All-of-Fabric-5#324]
When I try to join a server that I created using this mod (without adding or deleting anything) I always get this error. I tried to use one of my friends who can connect to server that his kubejs configs but the error gets more comlicated. Could you help me about this problem?

I am using TLauncher btw

net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:item contains IDs unknown to the receiver!
 - kubejs:aof5_logo

**Comment by Yoosk** [comment]
> I am using TLauncher btw

We do not support pirated launchers, buy the game and use one of the legit launchers, then we can help with your issues, if there will be any.
