### ISSUE TITLE
Cammies backpack issue

### ISSUE THREAD

**Issue by Stuffguy7** [TeamAOF/All-of-Fabric-5#327]
I had a white backpack on from cammies wearable backpacks, I placed a shulker with items in it inside of the white backpack, while wearing the backpack i right clicked on the shulker and items from inside the shulker were deleted.

**Comment by thinkingwithrice** [comment]
Adding to this, the issue works on chests, aswell. Found out by accident and deleted items. Further details: you can right-click items into the shulker while in another inventory, (chests, backpacks, etc), but right-clicking on the shulker with no items on your curser will delete the items in each slot 1-by-1. Right-clicking the box with ONLY your inventory opened will open the shulker like a backpack.
