### ISSUE TITLE
Bewitchment salt usage problem

### ISSUE THREAD

**Issue by GoldVinyl** [TeamAOF/All-of-Fabric-5#328]
For the Bewitchment mod, it appears as though you cannot place the Modern Industrialization salt to perform rituals. I may be wrong but I think the Bewitchment mod's salt is disabled.

**Comment by dandin87** [comment]
![image](https://user-images.githubusercontent.com/9329117/172063312-c10c728d-a6d7-4737-812b-2785cce91257.png)
If you press "r" on bewitchment salt it should show you how to get it.

**Comment by GoldVinyl** [comment]
> ![image](https://user-images.githubusercontent.com/9329117/172063312-c10c728d-a6d7-4737-812b-2785cce91257.png) If you press "r" on bewitchment salt it should show you how to get it.

Oh ok. My bad then, you can get the salt anyway. :P
