### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by MeikelLP** [TeamAOF/All-of-Fabric-5#329]
I use the following mods in my client on a vanilla server and really do miss these in this modpack:

Essential (in my opinion):
* [MAmbience](https://www.curseforge.com/minecraft/mc-mods/mambience) - big mod ~40MB
* [Falling Leaves](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric)
* [Mouse Wheelie](https://www.curseforge.com/minecraft/mc-mods/mouse-wheelie)
* [Sound Physics Remastered](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
* [3D Skin Layers](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
* [BetterF3](https://www.curseforge.com/minecraft/mc-mods/betterf3)
* [Presence Footsteps](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps)
* [Sheep Consistency](https://www.curseforge.com/minecraft/mc-mods/sheep-consistency/)
* [Giselbaer's Durability Viewer](https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer)
* [Extra Sounds](https://www.curseforge.com/minecraft/mc-mods/extrasounds)
* [Drip Sounds](https://www.curseforge.com/minecraft/mc-mods/dripsounds-fabric)

Optional/Opinionated:
* [Inventory Spam](https://www.curseforge.com/minecraft/mc-mods/inventory-spam)
* [LazyDFU](https://www.curseforge.com/minecraft/mc-mods/lazydfu) - Feel like it doesn't do much but it might do!

They are all updated and work in my patched modpack (I think `1.2.3`) instance.

**Comment by dandin87** [comment]
LazyDFU is in the pack already... As for at least half of those, they have a performance impact on low end hardware....

**Comment by MeikelLP** [comment]
They do yes. But they massively improve immersion.

**Comment by OweningIt** [comment]
Most of these are client side, just add them yourself if you want
