### ISSUE TITLE
The "Inventory Insertion" enchantment in the mod "Spectrum" doen not work

### ISSUE THREAD

**Issue by Nyanxikun** [TeamAOF/All-of-Fabric-5#330]
As the title says, I tried it on both an already enchanted netherite pickaxe and a normal diamond pickaxe, but neither of them put broken blocks into my inventory.

**Comment by dandin87** [comment]
Charm would be my only guess, as they have a similar enchant. I will test it out later.

**Comment by dandin87** [comment]
That is the enchant that is removed yes. Do you have the requisite Spectrum progression to use the Inventory Insertion enchant?
Also Charm only causes issues for <v1.2.0 worlds updated to 1.2.0+ otherwise it has no issue.

**Comment by Nyanxikun** [comment]
Yes, I just unlocked the spectrum enchanting yesterday and was trying out this new enchantment when I found this out
