### ISSUE TITLE
Delay when batch crafting

### ISSUE THREAD

**Issue by unilock** [TeamAOF/All-of-Fabric-5#332]
When crafting multiple of an item at once by holding SHIFT and clicking the output slot of the crafting table, e.g. 64 brick blocks from 256 bricks, there's a delay between when the first craft enters your inventory and when the rest of the crafts enters your inventory.

Video:
https://user-images.githubusercontent.com/11802133/172812274-c2eb3a0f-f095-4766-99a9-c8e9908a153e.mp4

Here, the delay was about a second. However, when I've experienced it, it ends up being around 5 seconds. (it adds up)
I believe the delay gets longer the more of the item you're crafting with you have in your inventory, and perhaps with the amount of time you've been in a world during one session.
(in this example, more redstone blocks and/or staying on the world longer = bigger delay, probably)

During the delay, you can exit the crafting interface (ESC) and walk away; the items still get crafted and will appear in your inventory as per usual, albeit not updating in number until opening some external interface or interacting with the item in your inventory.
Note that interacting with anything during the delay will do nothing, e.g. opening chests or another crafting table - until the delay has passed, in which case your interactions will go through. Perhaps it's a client-side bug, then?
(in this example, after crafting the redstone dust and before the rest of it enter your inventory, you can exit the crafting interface and walk around just fine. interacting with the crafting table again during the delay will do nothing, until the delay has finished, at which time the crafting interface will open again. (without further interaction))

The same issue occurs in both singleplayer and multiplayer, and has existed for quite some time; I remember this happening as far back as v1.1.3.

I tested [Improved Stations](https://www.curseforge.com/minecraft/mc-mods/improved-stations) specifically, and it was not the mod at fault.

**Comment by saltyseadoggo** [comment]
I can verify experiencing this as well; I had it most noticeably while crafting many stacks of Farmer's Delight rice bags. The delays were about 5 seconds in duration.

**Comment by unilock** [comment]
Still a problem on 1.4.1.

**Comment by KouramaProject** [comment]
Still an issue, i can add it kind of freeze/hang the server a fews seconds (high CPU usage), causing sometimes a small rollback of a fews MS.

**Comment by unilock** [comment]
[FastBench](https://www.curseforge.com/minecraft/mc-mods/fastbench-for-fabric) (+ [FastFurnace](https://www.curseforge.com/minecraft/mc-mods/fast-furnace-for-fabric)?) or [Recipe Cache](https://www.curseforge.com/minecraft/mc-mods/recipe-cache) might fix this, but I haven't been able to test yet.

Although it seems FastBench has some issues with [Improved Stations](https://github.com/shedaniel/improved-stations/issues/39). (Shame there's not an alternative to the latter, since it isn't compatible with [Crafting Tweaks](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks-fabric) either...)
