### ISSUE TITLE
Opening Death Log Screen crashes client

### ISSUE THREAD

**Issue by generalm13** [TeamAOF/All-of-Fabric-5#333]
As the title says: Trying to open the Death Log screen (Default key is END) results in the client crashing.
Rebinding the key to a different key yielded the same result

**Comment by ZestyBlaze** [comment]
Crash Log please?

**Comment by generalm13** [comment]
[latest.log](https://github.com/TeamAOF/All-of-Fabric-5/files/8883514/latest.log)

**Comment by generalm13** [comment]
Sorry forgot to include that, was having a bit too much fun last night XD
