### ISSUE TITLE
[AoF5 1.2.4] XP Shower not working as expected

### ISSUE THREAD

**Issue by trevorjd** [TeamAOF/All-of-Fabric-5#335]
Hi folks,

I've set up an XP shower but I can't make it rain. I have tested with various arrangements of tanks, and positions of the shower and lever. Even tried a redstone block. Image below is what I have at the moment and is as depicted on the Kibe mod page. I'm running on a private server but I've also tested in single player creative. Discord crew were very helpful with suggestions but we couldn't find a solution. Any ideas?

https://i.imgur.com/ISVawDi.png

**Comment by dandin87** [comment]
![image](https://user-images.githubusercontent.com/9329117/173197416-19cc8335-6e18-40c2-89cc-c2b6a5b18890.png)
Did you try flipping the level and shower positions? Also, FYI, you can drag/paste images into github now, so it will embed it

**Comment by trevorjd** [comment]
Thanks for the tip! 

Yes, I did try many different combos of tank config, head and lever. Under, over, head on upper, head on lower, head underneath, etc.

**Comment by sleepysadden** [comment]
Is it liquid xp from xp obelisk or kibe? Former doesn't work for much at all short of moving exp from one obelisk to another. To make it rain you'd need to fill the tank with Kibe liquid xp

**Comment by trevorjd** [comment]
Kibe's own, collected by standing on an XP Drain.

**Comment by trevorjd** [comment]
Was this fixed?
