### ISSUE TITLE
Tech Reborn, Modern Industrialization, and Industrial Revolution Metals

### ISSUE THREAD

**Issue by LloydAZ** [TeamAOF/All-of-Fabric-5#339]
We just upgraded our server from version 1.1.5 to 1.2.4 and I am really looking forward to playing with the Create Mod!

I just noticed that I was getting different types of the same metals than what I already had in my storage.  The metal could be from any one of these three mods.  This also changes some of the recipes when combining nuggets/ingots as to what you get back from the recipe.

For example: REI Shows that combining 9 of any of these three types of tin will return you a Modern Industrialization block of tin.  However, I am getting the Modern Industrialization version of the block.

Opening scrap boxes will also give you random versions of nuggets, for example I have both Tech Reborn and Modern Industrialization versions of the Tungsten Nugget.

Technically it's okay because they all seem to be able to be combined together and you will get one of these three versions of the ingot/nugget/block, but it's a bit painful for storage solutions.

**Comment by dandin87** [comment]
The kubejs folder messed up when you updated. I would delete it and reupload them.
