### ISSUE TITLE
Suggestion: Shnupbups mods

### ISSUE THREAD

**Issue by Shnupbups** [TeamAOF/All-of-Fabric-5#34]
hello yes i have mods to be added to aof5 perhaps please?
- [Sweet Tooth](https://www.curseforge.com/minecraft/mc-mods/sweet-tooth)
- [Cauldrons](https://www.curseforge.com/minecraft/mc-mods/cauldrons)
- [Quicksand](https://www.curseforge.com/minecraft/mc-mods/quicksand-fabric)
- [Gentle Picking](https://www.curseforge.com/minecraft/mc-mods/gentle-picking)

they are all very good and bug free

**Comment by Monster-Zer0** [comment]
monster said so.

**Comment by Shnupbups** [comment]
i want it made clear that i do not support the murder of those that don't support my modding efforts

but if those people did just so happen to one day spontaneously go missing...
