### ISSUE TITLE
FTB Ultimine conflicts with lumberjack enchantment taking more durability from axes

### ISSUE THREAD

**Issue by sleepysadden** [TeamAOF/All-of-Fabric-5#341]
Using FTB Ultimine with an axe enchanted with lumberjack on a tree which triggers lumberjack causes the tool to loose massive amounts of durability. Shapeless ultimine ona 2X2 holly tree with lumberjack trigger causes an unbreaking IV netherite axe at full durability to lose almost all of its' durability leaving only about 200 depending on the tree size.

**Comment by dandin87** [comment]
The simple answer is that you should not ultimine the tree when you have an enchant to do that. By using Ultimine in combination with your lumberjack enchanted axe, you are causing both to trigger taking away durability. So its costing twice as much.
