### ISSUE TITLE
Unable to start Server with Serverstart file

### ISSUE THREAD

**Issue by rivenluv** [TeamAOF/All-of-Fabric-5#343]
![image](https://user-images.githubusercontent.com/107653017/174187890-7e596842-7c99-4501-8ef0-50462114d3b2.png)

Above message appears when trying to open server.

What can I do to fix this?

Thanks!

**Comment by Seegras** [comment]
The last server pack containing the necessary files is 1.2.3 The newer ones aren't really:
```
All-of-Fabric-5-Server-1.2.3.zip    255796kb
All-of-Fabric-5-Server-1.3.0.zip    20kb
```
The new ones only contain start-scripts, icon and a yaml (which is used by some specific software?)
