### ISSUE TITLE
how do i apply more ram to the server ?

### ISSUE THREAD

**Issue by wiss209** [TeamAOF/All-of-Fabric-5#345]
my server of aof5 is a little bit short on memory so i want to asign more to it, could anyone help me?

**Comment by JensenButton9** [comment]
If you're hosting in on a system, you own then it's as simple as opening the server setup-config.yaml file and changing the max RAM.  
![image](https://user-images.githubusercontent.com/49365963/176793882-f6537118-aea2-4cdf-bf0e-d3d88e1c4261.png)

**Comment by JensenButton9** [comment]
Also, you can do /spark healthreport --memory and it will give you a breakdown of the server's memory usage.
![image](https://user-images.githubusercontent.com/49365963/176794078-9eac1fd5-7197-433a-85dc-d69945b1a6d6.png)
