### ISSUE TITLE
Add the grind enchantments mods

### ISSUE THREAD

**Issue by DonFlymoor** [TeamAOF/All-of-Fabric-5#347]
Since charm has been removed, we should add some mods to return some of it's functionality. One of the best features in my opinion is the ability to transfer enchantments onto books. The mod https://www.curseforge.com/minecraft/mc-mods/grind-enchantments should restore that functionality.

**Comment by unilock** [comment]
In my opinion, Spectrum's Enchanter would be more balanced than such a mod. It allows creating (vanilla) enchanted books from various materials, as well as duplicating enchanted books (from any mod) - at the cost of (a large amount of) EXP, of course.
It also allows upgrading enchanted books through similar mechanics, but AFAIK that's broken right now. (Thanks, KubeJS.)

I'm not sure, however, whether it can transfer enchantments *from* tools *onto* books. Maybe that's a bit overpowered, anyway ;)

I say Spectrum would be "more balanced" as it requires some effort to progress to and construct the Enchanter, unlike the Grindstone - not to mention collecting the materials to create enchanted books.

**Comment by dandin87** [comment]
We already have a mod to move enchants from items to books.
https://www.curseforge.com/minecraft/mc-mods/infusion-table
