### ISSUE TITLE
Worldgen biome mismatch between versions 1.2.4 and 1.3.0

### ISSUE THREAD

**Issue by GanaramInukshuk** [TeamAOF/All-of-Fabric-5#352]
I'm not sure to what extent this is fixable or gamebreaking (probably not much), but biomes that would be one type in 1.2.4 continue generating as a different type in 1.3.0. For example, one biome that was to be a savannah continues as a magical forest.

![2022-06-20_13 59 29](https://user-images.githubusercontent.com/5506045/174677440-f76b4c2c-d915-4d62-8087-47450a0a2d77.png)
 
![2022-06-20_13 59 29 - Copy](https://user-images.githubusercontent.com/5506045/174677802-a0f87f94-08da-4a4a-83f7-451f76018ffa.png)

**Comment by dandin87** [comment]
Not fixable. When BYG has updates to its biome generation (or any mod adding/removing biomes) then it remakes the biome map, aka which biomes are placed where. This causes biome chunk borders.
