### ISSUE TITLE
Perception enchantment from enchancement mod not working properly

### ISSUE THREAD

**Issue by TheUnknownOriginal** [TeamAOF/All-of-Fabric-5#354]
The perception enchantment for helmets is not working after the update of AOF to 1.3.0, while it is still working in 1.2.4

The enchantment allows us to see in the dark which is still working on both AOF version but the other function which is to see mobs around 16 blocks close to us to be highlighted through the wall is not working in 1.3.0. I tried to change the version of enchancement mod to the previous version (18 to 17 mod version) on 1.3.0 but its still the same, so im not sure if its due to other mods that affects it or not

**Comment by STK-Close** [comment]
Can confirm this one as well. The update to 1.3.0 disabled the ability.
