### ISSUE TITLE
[[ERROR] Crahses because of modded sign placed

### ISSUE THREAD

**Issue by Happysophie6** [TeamAOF/All-of-Fabric-5#355]
My game crashes every time I try to get into my modded server (we use All of Fabrics 5). the Error Code "The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4730.method_24145(net.minecraft.class_4597, java.util.function.Function)" because "$$12" is null
Exit Code: -1" shows up after the game crashes. I have my latest log and crash report you can also take a look at. It happened as soon as I placed down a modded sign - only the area and the players around it are affected by this. 
[latest (1).log](https://github.com/TeamAOF/All-of-Fabric-5/files/8948184/latest.1.log)
[crash-2022-06-20_18.51.27-client (3).txt](https://github.com/TeamAOF/All-of-Fabric-5/files/8948185/crash-2022-06-20_18.51.27-client.3.txt)

**Comment by dandin87** [comment]
Block: Block{byg:palm_wall_sign}
	Block location: World: (-642,65,-2727)
	Not sure why this crashes but you will need to delete this sign. Either by editing it out of the region file, or if you can get near it without it trying to render, then someone can use commands to replace with air. Or you can add world edit, and then the chunk doesn't have to be loaded, but a player does have to run the command.
	//pos1 -642,65,-2727
	//pos2 -642,65,-2727
	//replace air
Here is a mod that we had made. Run this command /resetspawn playername
and it will move your position back to world spawn. Hopefully that's not where the sign is.
https://cdn.discordapp.com/attachments/897220140192628746/903774208910315600/player-s-utils-0.0.1.jar

**Comment by kaylendog** [comment]
Likely an upstream issue in the latest Sodium version, issue tracked here: https://github.com/CaffeineMC/sodium-fabric/issues/1352

**Comment by dandin87** [comment]
[ufu.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/8960750/ufu.txt)
Place this file in the config folder. It will replace all instances of BYG signs in world with minecraft:air
