### ISSUE TITLE
Server crash when using Twilight Forrest's uncrafting Table

### ISSUE THREAD

**Issue by Throton80** [TeamAOF/All-of-Fabric-5#359]
Server crash when using Twilight Forrest's uncrafting Table

**Comment by JensenButton9** [comment]
![image](https://user-images.githubusercontent.com/49365963/176793234-a1cfe94a-556e-4ae9-b9c2-69b7ebe03732.png)
It's disabled for me by default, that could be a solution for now.

**Comment by ttamnedlog** [comment]
That's part of the problem. Even though it is disabled, the table is still attainable via chest loot and attempting to use the table causes a crash.

I did see a pull request that was accepted that uses kubejs to prevent all use and interaction with the table. If you don't want to wait for the pack to update, you could copy that into the configs yourself in the meantime:

https://github.com/TeamAOF/All-of-Fabric-5/pull/360/files
