### ISSUE TITLE
Poor performance after GPU upgrade

### ISSUE THREAD

**Issue by MeikelLP** [TeamAOF/All-of-Fabric-5#364]
Today I switched from my NVIDIA RTX 2080 to an AMD RX 6900 XT.

Somehow the performance got worse:

![2022-06-28_22 24 12](https://user-images.githubusercontent.com/11669846/176278315-ad9d4f3a-442d-40f4-950c-de7bbb7c46d2.png)

I reach at max 50 FPS. With my old card I never really dropped below 100.

How is this possible? Is there some cache I can clear up? If this is the wrong place please forward me to Sodium (or whatever matches best)

**Comment by notmaroun** [comment]
Did you uninstall your old drivers with DDU and do a clean install of AMD's drivers? Have you made any changes/updates to any mods?

**Comment by MeikelLP** [comment]
I did not fully remove my NVIDIA drivers no. I supposed they don't matter at all. Other games work fine (with massive performance boost).

No the game is unchanged.

**Comment by notmaroun** [comment]
Unlikely, my friend runs a 6900XT with AOF5 and runs it perfectly smoothly.

**Comment by MeikelLP** [comment]
@ProjectET even with poor opengl drivers this should run better than this. 

I wont switch to Linux just for one game.

Also your theory would mean that everybody that plays Minecraft on Windows with an AMD card would habe poor performance. Do your really think so?

**Comment by ProjectET** [comment]
yes AMD notoriously has bad opengl drivers and we have had people on amd cards experience this before https://www.techpowerup.com/295864/amd-significantly-improves-opengl-performance-in-windows-with-upcoming-22h2-driver

**Comment by MeikelLP** [comment]
Sorry but your post shows an improvement of ~10%. This is far away from what performance I am experiencing. I have more than 50% less performance than with my (~50% less performant) RTX 2080.

**Comment by ProjectET** [comment]
Just try booting a live linux usb and see if you experience this issue, if you dont its the drivers simple

**Comment by NickMesser** [comment]
> I did not fully remove my NVIDIA drivers no. I supposed they don't matter at all. Other games work fine (with massive performance boost).
> 
> No the game is unchanged.

I would try the old driver uninstall. Its always suggested especially if switching between nvidia and amd to uninstall previous drivers.

**Comment by MeikelLP** [comment]
@NickMesser I reinstalled every GPU driver on my machine (NVIDIA + AMD) and reinstalled AMD (drivers only). No change sadly. I also did everything in this video here: https://www.youtube.com/watch?v=14QSlEvvzoA

@ProjectET I saw this post: https://old.reddit.com/r/Amd/comments/l8e9d6/supercharge_your_fps_in_minecraft_java_opengl_by/ And according to that we should already have great performance in AOF5 due to Sodium but I'm not seeing that at all.

**Comment by MeikelLP** [comment]
Some other thing I noticed is that Minecraft says it's using OpenGL 3.x while my GPU/Driver has 4.x installed. Isn't Sodium like bringing 4.x to Minecraft?

**Comment by MeikelLP** [comment]
So I tried vanilla Fabric + Sodium. 500+ FPS. So something in AOF is broken OR I need to clear some cache (?)

**Comment by OverTasked** [comment]
Reinstall the pack

**Comment by MeikelLP** [comment]
Sadly even reinstalling didnt fix a thing. I tried dual booting with Ubuntu and it worked for some time. Sadly the performance started to degrade at some point similar to Windows.

I decided to stay with my Nvidia card and never ever touch AMD cards again.

**Comment by Nyfaria** [comment]
> I decided to stay with my Nvidia card and never ever touch AMD cards again.

Solid Decision
