### ISSUE TITLE
No way of naturally aquiring Platinum

### ISSUE THREAD

**Issue by GummiAuduns** [TeamAOF/All-of-Fabric-5#368]
If you've progressed in the Tech Reborn tree, you'll notice that there is no natural way of getting platinum in the game when you want to start advancing towards UU-matter. You can only get it from scrap boxes. And you need platinum plates to create Industrial circuits, and you need those for the blue lapotron crystals. So yeah.... the 10 or so dust I've got from scraps are not gonna cut it :'D

Please help with this since Tech Reborn is one of my favorite mods and I'd like to progress further.

**Comment by NxFals** [comment]
> If you've progressed in the Tech Reborn tree, you'll notice that there is no natural way of getting platinum in the game when you want to start advancing towards UU-matter. You can only get it from scrap boxes.

There are plenty of ways to get platinum. You can get it from Sheldonite Ore in The End. You can get them from quarries and ore cards.

**Comment by GummiAuduns** [comment]
Alright understood, but it doesn't seem really reliant, so it feels like the package could use some update in that regard. But I might try that. Thanks for taking the time to reply to the issue.

**Comment by NxFals** [comment]
Using crushing wheels from Create.

**Comment by vibratim** [comment]
This seems to work fine. But I really wanna use the techreborn machines. Could it made possible by adding the recipe to the (industrial)grinder ?
