### ISSUE TITLE
The twilight world issue In AOF5 1.30

### ISSUE THREAD

**Issue by JINANZ** [TeamAOF/All-of-Fabric-5#370]
In The New version of the 1.30 pack. There is no Boss drops When player defeat them. Both servers and single play have this  issue

**Comment by KuroPeach** [comment]
Look for a chest nearby and see if there is any?

**Comment by JINANZ** [comment]
Ok,Got it. tx :)

**Comment by JINANZ** [comment]
> Look for a chest nearby and see if there is any?

Ok,Got it. tx :)
