### ISSUE TITLE
Modern Industrialization: Quarry drills are not cost efficient

### ISSUE THREAD

**Issue by GummiAuduns** [TeamAOF/All-of-Fabric-5#374]
We went through 4 drills with hardly anything to show for. The drills have a 1% chance of being destroyed (Some 2.5%). This was our shimmer of hope for some sustainable ore gathering. This is the final straw for this modpack. Hitting delete and canceling server. Just wanted to let you know that this mod ruins the game for many players I would assume. You've gathered loads of resources just to hit a spot where you think you'll finally be satisfied just to find out that the drills completely vanish after a few ticks. This feels more like 10% chance of being consumed. The percentage should be removed or at least put to 0.01%. I know that this is not AOF's teams fault, just wanted to let you know if you wanna make changes to the mods in the modpack.

**Comment by unilock** [comment]
The official response from one of the devs of Modern Industrialization... is to craft more drills.
https://github.com/AztechMC/Modern-Industrialization/issues/121#issuecomment-913098120

Indeed, the Bronze Drill [does have a 1% chance](https://github.com/AztechMC/Modern-Industrialization/blob/de3b3e98cd95979da45168494bea0198315fe841/src/main/resources/data/modern_industrialization/recipes/quarry/bronze.json#L8) of being consumed every tick.

My personal solution would be to automate drill production as soon as possible - though this may be somewhat difficult, as you need drills to gather resources to process into the materials required to make drills... a feedback loop.

IMO, the probability of a drill being consumed should start low (or at 0!), then slowly increase every tick. I'll edit this comment once I open an issue on MI's repo.

**Comment by GummiAuduns** [comment]
Alright thanks, I wrote a reply to the other post you linked. I just feel like the 1% consumption is not correct, as our drills vanished quite fast. So the quarry is not a suitable option for people looking for ore generation as it costs insanely much and offers really no return on investment.
