### ISSUE TITLE
[BUG] Inventories being deleted when using waystones. Also when players travel thriugh the End Portal

### ISSUE THREAD

**Issue by OverTasked** [TeamAOF/All-of-Fabric-5#375]
I have been having a reoccurring problem on my AOF5 server where entire inventories have been deleted. I have been unable to consistently recreate it but it has happened three times by This point in the play through. It only appears to happen when using the waystones to cross dimensions. Any fix?
 Also a problem when travelling through the end portal

**Comment by OverTasked** [comment]
Also a problem when travelling through the end portal

**Comment by unilock** [comment]
I've never experienced this when going through an End Portal, neither from the overworld to The End, nor vice versa.
I can't speak for the Waystones, as I've never used them to traverse across dimensions.

Have you added or removed any mods from AOF5?
Could you screenshot your inventory before travelling across dimensions? A wild guess would be that you have one or more of Twilight Forest's "Charm of Keeping" on you, which interfere with inventory mechanics (upon death).

**Comment by OverTasked** [comment]
I have added a backup mod, but this was occurring before I introduced it. (I introduced it so I can restore the world if it happens)

**Comment by OverTasked** [comment]
It also continued after. The bug appears to delete all the parts of a normal vanilla inventory and not backpacks and trinkets.

**Comment by OverTasked** [comment]
Also I havent messed at all with Twiligh

**Comment by OverTasked** [comment]
Turns out we miss interpreted the issue, it appears to be a soul bound and gravestones conflict.
