### ISSUE TITLE
Inventory Hotbar Shifted/Cut-off

### ISSUE THREAD

**Issue by JooshDo** [TeamAOF/All-of-Fabric-5#376]
![2022-07-06_20 05 04](https://user-images.githubusercontent.com/24470307/177682695-a8e62521-e7e3-4aea-9c10-a5bf0c0b8c76.png)
My hotbar is now partially offscreen after everything being just fine the other day. I have already tried messing with many different resolutions in the Minecraft launcher hopes of fixing it, but nothing seems to change. I tried disabling shaders, fullscreen/windowed, and messing with my FOV as well to no avail. I am at a loss since I have not messed with any of my in game settings recently. What baffles me the most is the fact that my armor HUD is still seemingly in the proper place. Help.

**Comment by ttamnedlog** [comment]
Check your key bindings. You will find minus is bound to not only zooming out your minimap, but also to lowering your hotbar. You'll then see a keybinding for _raising_ your hotbar, which is unbound. Bind that to plus or something and raise the hotbar back to your liking.

There is a mod in the pack called "Raised" which raises the hotbar a few pixels off the bottom edge of the screen. Apparently, the hotbar's placement in the Java edition of MC is and has always been "incorrect," and if you look at the hotbar on Bedrock versions you can see how it should be.

For reasons I can't understand, that mod _also_ allows you to raise or _lower_ the hotbar to your liking. Why create a mod with the sole purpose of fixing a UI mistake and yet also allow the player to undo the fix? And, as you've discovered, even worsen the problem?

**Comment by JooshDo** [comment]
That was exactly it! I never knew such a mod existed to give us control over the height of our hotbar. The other day my hotbar was only like a quarter off the screen and I didn't think much of it, but it definitely was since the keybind to lower my hotbar was the same as zooming out my minimap. It's odd that the raise keybind for the hotbar was never bound by default, but oh well. Thank you for your knowledge and assistance!
