### ISSUE TITLE
Don't ship `expanded_storage.json` with the pack

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamAOF/All-of-Fabric-5#378]
New versions of All of Fabric 5 replace my Expanded Storage config for no reason, which causes headache for me as I have to exit the game and manually edit the `expanded_storage.json` file to change the chest display type back to what I want it to be after every single pack update. It also means that players don't get to see the mod's screen to choose their chest screen type when they open an expanded storage chest for the first time; the pack just forces the `single` screen type on them.

I would like to see future versions of All of Fabric 5 not ship `expanded_storage.json` in the config folder to prevent these issues.

**Comment by yorii** [comment]
This was already fixed at some point :)
