### ISSUE TITLE
Soul bound enchant conflicts with gravestones mod

### ISSUE THREAD

**Issue by OverTasked** [TeamAOF/All-of-Fabric-5#383]
Hey, I have had a few experiences with the soul bound enchantment not working and then the grave will not contain the item. It appears to just be deleted.

**Comment by ttamnedlog** [comment]
What version of the modpack are you on? That was supposed to be fixed in the most recent 1.3.1 version.

**Comment by OverTasked** [comment]
Ahh ok I'm on a slightly outdated pack

**Comment by OverTasked** [comment]
I'm just on 1.3.0
