### ISSUE TITLE
serverstarter shows enigmatica as discord link

### ISSUE THREAD

**Issue by Quezler** [TeamAOF/All-of-Fabric-5#385]
hi,

member of the [enigmatica discord](https://discord.com/channels/195234321836146688/998251266532704417) server here, we've had two people come to us for help with the serverstarter since that one has our discord link in it, could you modify your server files so it points to your own discord? (so people get sent to the right place) 😇 

- 7th of july https://discord.com/channels/195234321836146688/993329422868435064
- 17th of july https://discord.com/channels/195234321836146688/998251266532704417

**Comment by ImAK9** [comment]
Hmm, not sure where this is done.. Most likely within the jar, I'll have a look when on PC or reach out to Niller.

**Comment by ImAK9** [comment]
Is branding done anywhere than here?
https://github.com/TeamAOF/ServerStarter/commit/a8a6e1ff2eaf0ed17f43335380b4f5a9cfe552c5

**Comment by ImAK9** [comment]
https://github.com/TeamAOF/ServerStarter/releases/tag/v2.4.0
