### ISSUE TITLE
Suggestion: LambDynamicLights

### ISSUE THREAD

**Issue by NiChrosia** [TeamAOF/All-of-Fabric-5#39]
[Curseforge link](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights)

**Comment by Monster-Zer0** [comment]
maybe, in past it has done some weird performance things.. but with my testing of it on skylore.. it had zero to little affect. We will have to test to double check.

**Comment by NiChrosia** [comment]
Haven't had any issues with my experience with it on AOF5, although that's just a few hours of testing.
