### ISSUE TITLE
Remove `carrier` mod for now

### ISSUE THREAD

**Issue by XyLyXyRR** [TeamAOF/All-of-Fabric-5#390]
remove `carrier` mod for now due to GabrielOlvH/Carrier#58

**Comment by dandin87** [comment]
Looks like it works so long as you have something in your main hand. So it has a work around for now. And no, we do not simply remove mods because of 1 issue that hasn't yet been fixed. We work with mod devs to get these kind of issues resolved.

**Comment by XyLyXyRR** [comment]
Okay, thanks for your response.
