### ISSUE TITLE
Cammies Minecart Tweaks causes minecarts to skip rails, and fly off like a plane at random intervals

### ISSUE THREAD

**Issue by ImPixxi** [TeamAOF/All-of-Fabric-5#394]
Steps to reproduce:
1. make a looping rail
2. put a minecart on it
3. push it off and wait for it to fly off the rail

![2022-08-01_00 34 59](https://user-images.githubusercontent.com/75047207/182079138-9cc857f0-b640-4ba9-9032-fa16e2bc6a71.png)

**Comment by midnighterror51-crypto** [comment]
yes bro yes
