### ISSUE TITLE
Update Create Mod to 0.5 (latest patch)

### ISSUE THREAD

**Issue by Fuggschen** [TeamAOF/All-of-Fabric-5#395]
Create pushed on 12th of July a new update with new blocks and trains and many fixes. Would love to see that in this modpack

**Comment by Yoosk** [comment]
No, create for fabric did not have official public release for 0.5 version yet.

**Comment by Fuggschen** [comment]
> No, create for fabric did not have official public release for 0.5 version yet.

Oh sorry. Misread it than on modrinth. Will reopen when the update is out
