### ISSUE TITLE
[Recommendation] Dashloader

### ISSUE THREAD

**Issue by Carterpersall** [TeamAOF/All-of-Fabric-5#4]
Dashloader is a mod that caches the game's content. After the first startup it greatly increases start times(6x advertised but often faster). But it can be a bit iffy in terms of mod compatibility. Currently though it seems to be compatible with every mod currently in AoF5 but if added should be kept in mind in the case of a new mod causing issues.

[https://www.curseforge.com/minecraft/mc-mods/dashloader](url)

**Comment by Monster-Zer0** [comment]
we are aware of dashloader. as soon as we get a wider set of mods in the pack we will be sure to test it.
