### ISSUE TITLE
Can't craft Tech Reborn Grinder

### ISSUE THREAD

**Issue by MozzieBytes** [TeamAOF/All-of-Fabric-5#400]
Hi!

I hope I find you well!

I'm currently playing on an AOF5 v1.3.1 (Minecraft 1.18) server  with my friends, and got stuck at a certain point in the Tech Reborn tree as I can't craft a Grinder despite having all of the ingredients :) 

Would it be possible to get this investigated?

I have attached some images as evidence!

![Too many items recipe preview](https://user-images.githubusercontent.com/15324906/183307568-ec61f81d-2c93-4708-821e-2beadc38a9bb.png)
![Everything in a craft bench](https://user-images.githubusercontent.com/15324906/183307585-0b500618-7c8d-4859-8b9d-43476f553b7d.png)

**Comment by xxtg666** [comment]
the REI recipe is wrong.
replace the copper block with indrev:fan
