### ISSUE TITLE
[1.5.1] There are no squid

### ISSUE THREAD

**Issue by ttamnedlog** [TeamAOF/All-of-Fabric-5#404]
There are no squid. If you search 'squid' in Discord, you'll see chatter about the lack of squid going back for months. So it apparently isn't just me.

There are glow squid. Just no regular squid.

If I stand near a river and _repeatedly_ run a command to kill all non-player entities, a few squid _eventually_ spawn. I suspect the passive mob spawn cap (if that's a thing) or aquatic spawn cap (if that's a thing) is quickly being clogged up by all the other mobs before the squid have their chance.

Just thought I'd mention this in hopes maybe something can be done for 1.4 or 1.4.1.

**Comment by TheSnowyChickens** [comment]
Yes, I also can't find squids in the world.

**Comment by ttamnedlog** [comment]
Just made a 1.4.1 world and found squid immediately, so I'll go ahead and close this.

**Comment by TheSnowyChickens** [comment]
Do you tried it on a server ? (my play map is on a server)

**Comment by unilock** [comment]
This has not been fixed, at least not server-side. I'm running AOF5 1.5.1 on both the client and the server, and one of my players searched an ocean for squid for an hour to no avail.

**Comment by ttamnedlog** [comment]
You're right. There are zero squid on my server still, having upgraded to 1.5.1.

**Comment by Kyzoku** [comment]
No squids spawning in new single player world on version [2.0.4].  Explored oceans for a little over an hour.

**Comment by yorii** [comment]
Nuhuh don't try it! I found squid on the EU server just yesterday!

**Comment by Kyzoku** [comment]
I don't know what to tell you.  I even used the command /execute at @e[type=squid] run tp @p ~ ~ ~ and nothing happened.

**Comment by mcd1992** [comment]
Noticing squid spawns are very rare on 2.0.4 as well. Have seen them but only once in an ocean and no more have spawned since.

**Comment by Kyzoku** [comment]
I think it is because all other mob spawns are lowering the priority for squid to spawn.
