### ISSUE TITLE
How can I reenable the uncrafting table 

### ISSUE THREAD

**Issue by Dannieboi** [TeamAOF/All-of-Fabric-5#408]
I removed the uncrafting table from the removals Javascript buts its still disabled?

**Comment by yorii** [comment]
> I removed the uncrafting table from the removals Javascript buts its still disabled?

It is disabled in the twilightforest config as well, but be warned that there is another issue with it that makes it crash. It is therefore unusable for technical reasons as well until a fix is released by Twilight Forest.

**Comment by AlphaMode** [comment]
The problem isn't cause by twilight forest iirc it's caused by ae2

**Comment by yorii** [comment]
> The problem isn't cause by twilight forest iirc it's caused by ae2

Haha, is it crashing because of all the recipes for facades? :D
