### ISSUE TITLE
Matching Recipes, is there way i can fix this? 

### ISSUE THREAD

**Issue by adminPants** [TeamAOF/All-of-Fabric-5#409]
Macaw's Trapdoors
![Screenshot 2022-08-12 141234](https://user-images.githubusercontent.com/69860649/184427782-0af5d8d1-92d1-44df-82de-b90c63ad2749.jpg)
Macaw's Fences and Walls
![Screenshot 2022-08-12 141323](https://user-images.githubusercontent.com/69860649/184427783-9ff353cb-6367-4af0-ad24-60af07c932a4.jpg)

**Comment by ImAK9** [comment]
Fixed in 1.4
