### ISSUE TITLE
Suggestion: Industrial Revolution

### ISSUE THREAD

**Issue by NiChrosia** [TeamAOF/All-of-Fabric-5#41]
It's now ready for 1.18.1 since [this commit](https://github.com/GabrielOlvH/Industrial-Revolution/commit/9867e98bb095796e0a1f9e126da71a624c99885b#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19R5), and Steven says [it's ready](https://user-images.githubusercontent.com/57579569/147388555-f0435799-e9b2-4a9f-ad16-d04d7a90f029.png).

[Curseforge](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution) link purely for convenience.

**Comment by Monster-Zer0** [comment]
NiiiiiiiiiiiChrosia.

what up homie?

life treating you good?

at any rate, thanks for the heads up. Yeah I saw that he even fixed the world gen a bit.

Trent and I will have to get a new version out soon.

**Comment by NiChrosia** [comment]
Yeah, doing well, looking forward to actually fully automating stuff.
