### ISSUE TITLE
Server crash when in area of item pipe from dank to extra generators

### ISSUE THREAD

**Issue by Wtfigohere** [TeamAOF/All-of-Fabric-5#42]
When using modern-industrialization item pips to move ender pearls from dank to extra generators server crash on login if in area.
server will load fine and other players can log in if not in the area. as soon as player gets in area of the above server crash.
Update modern-industrialization and fabric-api on server/client same error.
[crash-2021-12-25_12.32.05-server.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/7776169/crash-2021-12-25_12.32.05-server.txt)

**Comment by dandin87** [comment]
The issue is with the dank dock. Using item pipes on it for automation is not going to work until Dank uses the Fabric Transfer API. I suggest using a hopper on the dock into a chest then item piping from that.

**Comment by Wtfigohere** [comment]
Thank you for that info. do you know of a way i can load this world in and remove it with out crashing?
