### ISSUE TITLE
Modern Industrialization Tungsten dust cannot be smelted into a ingot

### ISSUE THREAD

**Issue by Aeonsfury** [TeamAOF/All-of-Fabric-5#425]
![tungsten dust](https://user-images.githubusercontent.com/92283637/185100332-bec4fb23-3f92-4b8a-af2d-47c503b88a33.png)

Tungsten dust does not have any recipes to be smelted into a ingot like other dusts. Instead you have to turn it into 9 tiny dust, then use a electric compressor to turn it into a nugget then recombine.

**Comment by unilock** [comment]
Yes, that's intentional.

**Comment by yorii** [comment]
As stated, tungsten is intentionally different.
