### ISSUE TITLE
Modern Industrialization armor and sword are too powerful

### ISSUE THREAD

**Issue by DonFlymoor** [TeamAOF/All-of-Fabric-5#428]
## Issue
Modern Industrialization armor can protect you from any damage and the sword can one hit every single entity, except players wearing Modern Industrialization armor. 

## Solution
This is insanely overpowered, and either be balanced or made unobtainable. 
It can be balance to make it remove %80 of damage with the full set, and the sword should only deal 30 damage.

**Comment by yorii** [comment]
This is 100% intended and a very suitable reward for anyone with the determination required to actually finish MI.
I really don't agree with this issue whatsoever.

**Comment by dandin87** [comment]
uh, yeah. Whats the hours required for this? 100+? So totally worth it. The pack also isn't geared towards PVP. On our servers we have a mod for Toggling PVP, so everyone has PVP off by default but can enable it if they choose. Perhaps your server could add the same thing.

**Comment by yorii** [comment]
> 100+?

I would say more probably, it's like 100+ if you actually put a lot of effort into it, probably 200+ for a less serious player.

**Comment by yorii** [comment]
For comparisons sake look at a maximum enchanted netherite bow (you need to also finish spectrum for this, so it's also 100+ hours required tho), which can:

Be used to kill every single boss in the game with very high dps (not as high as a gamer axe, but still very high).
Be used to CHEESE most bosses by just flying at max range with a jetpack and killing them from afar.
Also oneshot players if you have pvp enabled, but from a 1000x longer range.

It is _way_ more powerful than the sword from MI, and possibly easier to attain.

**Comment by DonFlymoor** [comment]
It's not the sword that's the most overpowered, it's the armor. Being completely indestructible, even /kill can't hurt you..

**Comment by yorii** [comment]
> It's not the sword that's the most overpowered, it's the armor. Being completely indestructible, even /kill can't hurt you. 99% damage removal would make more sense, so you're almost indestructible but not completely.

I really don't see what the difference would be between 99% and 100%, with one you can't go afk while being attacked?

**Comment by DonFlymoor** [comment]
%100 means you can't die. %99 percent means that a 20 damage sword will do 0.5 damage, or another MI sword can kill you.

**Comment by Yoosk** [comment]
> %100 means you can't die. %99 percent means that a 20 damage sword will do 0.5 damage, or another MI sword can kill you.

Wrong, that's not how the quantum armor works in here. 99% would mean that you have 99% chance to avoid any and all damage, not damage reduction.

**Comment by DonFlymoor** [comment]
https://wikimedia.org/api/rest_v1/media/math/render/png/47d118159dfd7e90693920c9bba7c81bf5d4d026
https://minecraft.fandom.com/wiki/Armor#Mechanics

**Comment by yorii** [comment]
Sorry but we're not going to do that. If you want to remove it yourself you can use KubeJS to do so.
