### ISSUE TITLE
Platinum Ingots too easy recipe with Create

### ISSUE THREAD

**Issue by yorii** [TeamAOF/All-of-Fabric-5#442]
As per the title, the Create recipe for Platinum Ingots is way too easy when compared to the MI and TR methods of procesing Platinum.

**Comment by dandin87** [comment]
Already fixed in Release? and if not in Dev. Can't always post things from the server, when its not updated yet.

**Comment by yorii** [comment]
ah, I am stuck living in the past playing on 1.4.1 server smh
