### ISSUE TITLE
Uncrafting Table unusable - leaves unbreakable ghost block behind

### ISSUE THREAD

**Issue by dschuess** [TeamAOF/All-of-Fabric-5#450]
Hey AoF5 Team,

We are experiencing problems with the uncrafting table from the twilight forest mod. After placing it, it cannot be interacted with, except for trying to break the block, which yields the block, but leaves a ghost uncrafting table, which is still there after breaking it an endless amount of times and a whole server restart, etc didn't help.

Here it is placed within the base, where it cannot be removed. Other blocks can be placed within but are back in ones inventory after a server restart.
![image](https://user-images.githubusercontent.com/7019602/188244347-2d003354-8d68-44ff-867e-f281a4d69aa3.png)

The broken uncrafting table can be placed anywhere else and is again not interactable. No right click UI, no actual breaking the block.

With the ghost block still within the base, we went into the twilight forest and placed it there, same thing - no interaction possible to uncraft items. Breaking it the first time, again yields the block, after that there is a persistent ghost block present, which cannot be removed.

Although I only found one uncrafting table, you can clearly see the ghost block and the actual item being in my hotbar, after trying to break it.
![image](https://user-images.githubusercontent.com/7019602/188244894-d8e69ec0-dd97-48b7-b9d2-293563b48981.png)

Is there any way to get it to work? We are playing on 1.5.1 on a dedicated server.

**Comment by 1552980358** [comment]
I met the same problemm, the uncrafting table cannot do anything with right click, and cannot be broken with anything.
But I found a solution to remove the block —— to use command `/setblock <x> <y> <z> air`, i.e., replace the xyz location with nothing. Try if you are playing on server, set yourself as op, and remove it with command.

**Comment by yorii** [comment]
We need a better KubeJS override script for this.
