### ISSUE TITLE
Method for getting Iridium is way too hard 

### ISSUE THREAD

**Issue by nugggyyyyy** [TeamAOF/All-of-Fabric-5#457]
It shows that Iridium ore can be found at y levels -64 to 16 when holding shift over iridium ore int he sides bar, but it does not show that it spawns anywhere in the overworld and the only other way of getting it is by making a titanium drill for the Eletric quarry, please make it easier i love this modpack but its too hard to grind

**Comment by Itplayz** [comment]
Try getting UU-Matter from tech reborn and crafting Iridium Ore with it

**Comment by nugggyyyyy** [comment]
thanks working on its its hard you never really get any from scrap boxes

**Comment by yorii** [comment]
Iridium ore does not spawn in the world, the difficulty of getting platinum is an intended feature.
