### ISSUE TITLE
I can only jump half a block

### ISSUE THREAD

**Issue by angefco** [TeamAOF/All-of-Fabric-5#464]
From one moment to another I can only jump half a block for some strange reason, I don't know what it could be

**Comment by angefco** [comment]
And i cant  jump on the water, i dont know why , i just got this boots , even if i unwear the boots i got the double jump 
![2022-09-23_05 49 08](https://user-images.githubusercontent.com/114135776/191945244-76cd7be7-6296-427a-8f27-d51b6aa02200.png)

**Comment by DaFuqs** [comment]
Fancy red dye you got there from your nether trip. You may want to stash that

**Comment by angefco** [comment]
Nice note,  but there's a way to reset artifacts "powers" on the server config? I think that should fix this

**Comment by yorii** [comment]
This is intended behaviour, and the "nice note" is actually your solution.

**Comment by angefco** [comment]
Oh man i feel like stupid , ty that was the solution

**Comment by yorii** [comment]
> Oh man i feel like stupid , ty that was the solution

;)
