### ISSUE TITLE
No way of getting platinum plates

### ISSUE THREAD

**Issue by J4ncHy** [TeamAOF/All-of-Fabric-5#465]
No way of getting platinum plates without initially already getting platinum which creates a paradox.

I can get raw platinum from MI but can't do anything further with it. 
I tried building crushing wheels with Create, finding iridium ore to get platinum dust but it doesn't seem to spawn (went into a new world and mined whole chunks and I haven't found it), UU-matter needs the matter fabricator which needs a lot of platinum plates to make.

**Comment by yorii** [comment]
This isn't correct, there are ways of getting platinum that don't require platinum.
