### ISSUE TITLE
Server File Error

### ISSUE THREAD

**Issue by Naoumxx** [TeamAOF/All-of-Fabric-5#466]
Hello, I am having trouble starting my server file. This server was running just fine using Bisect Hosting, but I downloaded all the files and am now attempting to run it from my local machine. 
[serverlog.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/9641840/serverlog.txt)

**Comment by Yoosk** [comment]
You ran vanilla server instead of modpack, also 2GB RAM won't be enough

**Comment by yorii** [comment]
You need to start it with the correct file, or create your own launch line.
