### ISSUE TITLE
Platinum dust almost impossible 

### ISSUE THREAD

**Issue by GreenKiller7** [TeamAOF/All-of-Fabric-5#468]
It is impossible to obtain platinum dust. For Tech Reborn mod Platinum dust is very important material in late game and you need it to create hot platinum and later platinum plates. But the only way to get platinum is to find Iridium ore which is very rare. I already mined few chunks and got 0 Iridium ore. You should bring back recipe from Tech Reborn where you can get platinum dust by grinding Sheldonite ore in industrial grinder. Now we get raw platinum and it is useless if we can't even smelt it.

**Comment by yorii** [comment]
This is intended, some other changes may be done in the future, but the overall method for making platinum will not change any time soon.

**Comment by scorp25** [comment]
There are two ways to get platinum. It's either do modern industrialization stuff by crafting electric quarry and titanium drill to get indium ore or trade with oceanographer and by trading many heart of the sea and put them in industrial grinder (TR) and you get small pile of platinum dust then craft platinum dust.

**Comment by vibratim** [comment]
Sounds a little counterintuitive but thanks a lot for your help :)
Would like to reintroduce the sheldonite ore variant.
