### ISSUE TITLE
Default texture pack overriding custom texture pack for hotbar gui

### ISSUE THREAD

**Issue by JBeytell** [TeamAOF/All-of-Fabric-5#473]
After creating a texture pack with hotbar gui, tested to all be working fine but when loaded within AOF5 the default hotbar gui overrides the custom one.

**Comment by 800020h** [comment]
you need to change buttons.png in the config for slight gui modifications

**Comment by yorii** [comment]
yeah as 800020h mentioned, we use Slight GUI Modifications: https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications

Most of, if not all of, the UI elements have their textures replaced with textures from this mod.
