### ISSUE TITLE
[2.0.0] quest book description for Iron Chest is misleading

### ISSUE THREAD

**Issue by ttamnedlog** [TeamAOF/All-of-Fabric-5#474]
The quest book for the iron chest in the storage chapter of the quest book states:

"Can be placed both horizontally and vertically."

I think that's a holdover from the previous chest storage mod. The new Iron Chests mod doesn't seem to have that functionality.

**Comment by sayore** [comment]
this is so sad

**Comment by yorii** [comment]
F
