### ISSUE TITLE
Void blossom boss immediately crashes the client

### ISSUE THREAD

**Issue by scriptis** [TeamAOF/All-of-Fabric-5#487]
On 2.0.2, being able to see a void blossom boss (which can spawn randomly in the world) will immediately crash the client.

Just hop into singleplayer and spawn one; issue affected both me (on Linux) and a friend of mine (on Windows)

**Comment by yorii** [comment]
uh oh...

**Comment by yorii** [comment]
Download the new BOMD-1.3.9-1.18.2.jar and replace the current version.

This will be fixed in 2.0.3
