### ISSUE TITLE
Hephaestus and FTBUltimine dont work

### ISSUE THREAD

**Issue by mcnerd73** [TeamAOF/All-of-Fabric-5#491]
Created a pickaxe and tried using it with FTB Ultimine. When holding down the grave key, Ultimine says how many blocks will be broken, however only one block is broken.  Using version 2.0.3.

**Comment by CheeseMan2400** [comment]
As far as I know from discussion on the discord, this is just a result of how tinkers is coded. And it has its own vein mining tool called the vein hammer.

I could be wrong though.

**Comment by mcnerd73** [comment]
Confirmed working in 2.0.5.
