### ISSUE TITLE
spectrum config out of date

### ISSUE THREAD

**Issue by 800020h** [TeamAOF/All-of-Fabric-5#494]
this makes it impossible to progress through spectrum
because terralith removes minecraft:swamp
so Quitoxic Reeds are unobtainable with the currently used config

**Comment by 800020h** [comment]
it seems terralith doesn't remove minecraft:swamp
some has been found on the EU server
I have not been able to confirm if Quitoxic Reeds have generated or not
but I can't see many places they could

**Comment by DaFuqs** [comment]
If the spawn conditions are quite bad (not a lot of clay in shallow water) the most recent versions also have a config setting to pump up the generation chances, so the chance of plants generating on the few valid places will be more probable.

**Comment by anagram3k** [comment]
Using the biome compass I found 3 swamp biomes (2 small and 1 medium size), flying about 1000 blocks and trying the compass again. Never been able to find a quixotic reed.

**Comment by Linguardium** [comment]
can confirm, swamp generation provides almost no potential spawn locations. Flew around 7-8 large biome swamps and found no quixotic reeds.  i found quite a few "reeds", "cattails", and sugar cane though.  Looking at clay generation is was mostly absent from the swamp generation, and where it was, it was several levels below waterline, which is likely why they are nearly impossible to find.  Seems terralith was a mistake without full testing through each mod.....
