### ISSUE TITLE
Ad astra steel plate recipe vanished

### ISSUE THREAD

**Issue by inkiingman** [TeamAOF/All-of-Fabric-5#497]
Hey. Thank you for the amazing modpack!
Noticed that in 2.0.4 ad astra steel plate recipe vanished. Cheers.

**Comment by yorii** [comment]
That's intentional, they should be replaced by MI steel plates.

**Comment by inkiingman** [comment]
Ah Ok that’s fine. However noticed this cause couldn’t craft ad astra items. I believe those recipes still require its own plates.

**Comment by yorii** [comment]
Oh, can you provide a list of the non-craftable recipes?

**Comment by Petko6** [comment]
Everything that uses steel plates from Ad astra can't be crafted, because the plates from the mod aren't craftable.
![Image of one recipe](https://user-images.githubusercontent.com/61025416/196033715-45a89e82-48a3-4afd-8277-193b09af827b.png)
Please change the recipes to use other mods plates.

**Comment by Petko6** [comment]
I have my world hosted on bisect hosting and it is from 1.x of the modpack Could that be a problem? How can I fixed that?

**Comment by inkiingman** [comment]
Me and Petko6 seem to have the same issue. All ad astra recipes that use steel plates are not craftable at the moment. 
However tried this on single player and there recipes work fine. On single player Ad astra recipes accept MI steel plates. But not on our server. We are running on aternos and our world was also created with 1.x series...

**Comment by yorii** [comment]
Can you try deleting and replacing the kubejs folder on the server with the kubejs folder from github?

**Comment by inkiingman** [comment]
I'm ... not sure. Not sure if I'm able to do something like that on aternos hosting. Tried to have a peek but couldn't see kubejs folders anywhere.

**Comment by Petko6** [comment]
> Can you try deleting and replacing the kubejs folder on the server with the kubejs folder from github?

I tried that now and it didn't help, maybe some of the data is in other folders.

**Comment by yorii** [comment]
> I'm ... not sure. Not sure if I'm able to do something like that on aternos hosting. Tried to have a peek but couldn't see kubejs folders anywhere.

That sounds like the entire issue, you must have the KubeJS folder and all the scripts contained therein to make the pack functional.

**Comment by yorii** [comment]
Actually there is a secondary mod now also part of the unification, called Almost Unified.
It should have a folder under config/almostunified/ with another set of files.

**Comment by Petko6** [comment]
> Actually there is a secondary mod now also part of the unification, called Almost Unified. It should have a folder under config/almostunified/ with another set of files.

Replaced those still nothing. Couldn't something be in the world file?

**Comment by yorii** [comment]
> Couldn't something be in the world file?

No, the world file should have no effect at all on recipes.

**Comment by AlexNijjar** [comment]
I have the same steel unification issue after downloading the pack from bisect. I think they’re not downloading the unification script properly.

**Comment by Petko6** [comment]
> I have the same steel unification issue after downloading the pack from bisect. I think they’re not downloading the unification script properly.

I even tried to reinstall the pack on bisect, but the issue still persists.

**Comment by Petko6** [comment]
> I have the same steel unification issue after downloading the pack from bisect. I think they’re not downloading the unification script properly.

I copied all the configs from this repo and the issue is still the same. Single player is fine tho. Maybe some error in the kubejs server script?

**Comment by inkiingman** [comment]
Just to let you know. Tried to troubleshoot this issue and the only root cause that seems consistent is the fact that our world was originally generated back in the 1.5.x era. I couldn't reproduce this issue in any of the worlds that get generated in 2.x era. 

This actually made us decide to move to a new 2.x world. Who knows what other similar issues might be there hurting our gameplay. Loosing the buildings was deemed acceptable but trying to bring all our stuff in player inventories and player data files to the new server. Wish us luck.

**Comment by yorii** [comment]
If you still have the old world, can you try removing or disabling the mod "Almost Unified"?

**Comment by Petko6** [comment]
> If you still have the old world, can you try removing or disabling the mod "Almost Unified"?

They told me that on discord too. I removed it and it works the steel plate now has a recipe in the ad astra's compressor.
