### ISSUE TITLE
Some farmland not hydrating and grass not spreading

### ISSUE THREAD

**Issue by dillonwastaken** [TeamAOF/All-of-Fabric-5#5]
I'm not sure what triggers it, but at some point my farmland stopped hydrating and grass stopped spreading. Seeds planted on the dehydrated farmland (which should be hydrated) also do not grow at all.

![2021-12-10_13 01 38](https://user-images.githubusercontent.com/40649376/145542470-0a314cc7-ce06-435f-a5f5-b363327c5eb8.png)
In the screenshot, I tilled both rows of farmland at the same time but only the right side seems to get hydrated and the seeds grow on it.

**Comment by dillonwastaken** [comment]
I removed the Kibe chunkloader and it seems to have fixed it

**Comment by ceasefyre** [comment]
I ran into the same issue with kibe chunkloader preventing crop growth and soil hydration. Disabling the 'forced' option in the loader for the chunk with the crops also allows it to tick normally. Raised as an issue on the kibe mod.
