### ISSUE TITLE
Can't Right click.

### ISSUE THREAD

**Issue by RedDeadKing92** [TeamAOF/All-of-Fabric-5#528]
I can't right click. Whether on the server or in single player. All other modpacks go. But right-clicking in the inventory works, I can move and split items. Even the crafting table I can right click to open a crafting panel but I can't interact in the world

**Comment by dandin87** [comment]
You have a tinkers chest equipped that is breaking right click. Remove it and it will work. We are aware of the issue, no eta on a fix.

**Comment by RedDeadKing92** [comment]
No, I don't wear armor.

**Comment by RedDeadKing92** [comment]
When I go to a server I get a message and the second time I can access the server without a message.

Connection Lost:
Internal Exception: io.netty.handler.codec.decoder.exception: java.lang.illegal.stateException: Attempted to load a Modifer before dynamic modifiers are loaded

**Comment by dandin87** [comment]
If you are not wearing armor, you might have picked something up with Carrier. If that's the case it prevents block interaction, and causes slowness and hunger. If you Shift+Rclick with empty hands you should be able to place whatever you might have picked up. If its not that then I'm not sure what else could be preventing it.
"Attempted to load a Modifer before dynamic modifiers are loaded" is a know issue. No fix yet.

**Comment by RedDeadKing92** [comment]
I don't think you understand. I haven't played 5 minutes yet.

**Comment by 800020h** [comment]
check your keybinds for conflicts
I know there was one with chisels and bits

**Comment by RedDeadKing92** [comment]
> check your keybinds for conflicts I know there was one with chisels and bits

Yes that helped. The key was indeed with Shift and right click but when I deleted it worked
