### ISSUE TITLE
Issue with Hephastus Slurping/Spilling effects.

### ISSUE THREAD

**Issue by DrMkdaddy** [TeamAOF/All-of-Fabric-5#532]
After repeat right clicks on a gauge, tank, and smeltery drain. Its been near impossible to fill the helmet, sword, or anything with a fluid. Could there be any potential conflicts or issues with Hephastus? issues have been appearing as well when attempting to use the armor abilities as well.

**Comment by Linguardium** [comment]
https://github.com/Alpha-s-Stuff/TinkersConstruct/issues/29 known bug, reported to mod dev already. nothing the pack dev can do to fix it since the mod itself is bugged
