### ISSUE TITLE
The "test" for working internet 

### ISSUE THREAD

**Issue by boldymann** [TeamAOF/All-of-Fabric-5#535]
Hi,

I want to install All of Fabric 5 server but  there  is a test if my internet is working?

Please use an URL that actually works please. example.com is not working. Have u test this?
But for everyone, please remove it. 

have a nice day! and thank u!

![Schermafbeelding 2023-01-02 155309](https://user-images.githubusercontent.com/22682140/210247638-1123b1b0-007d-4d2d-92ac-830b9ea5f471.png)

**Comment by z2969519442** [comment]
![image](https://user-images.githubusercontent.com/59475034/211177976-2b76f905-4c75-4cc4-b7c7-ef80f27eb178.png)

**Comment by Linguardium** [comment]
you can disable the checks if your internet provider blocks certain sites. open the yaml file and change `checkOffline` to false

**Comment by boldymann** [comment]
Thank you. I did not know that it was an option.
