### ISSUE TITLE
The game crashes when I try to load the map. 0.2.7(Exception in server tick loop)

### ISSUE THREAD

**Issue by LianLian2001** [TeamAOF/All-of-Fabric-5#55]
---- Minecraft Crash Report ----
// My bad.

Time: 1/3/22, 5:57 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:556)
	at java.base/java.util.List.of(List.java:1043)
	at net.minecraft.class_6686.method_39055(class_6686.java:314)
	at ru.bclib.world.biomes.BCLBiome.lambda$setSurface$2(BCLBiome.java:370)
	at ru.bclib.world.biomes.BCLBiome.updateActualBiomes(BCLBiome.java:245)
	at ru.betterend.registry.EndBiomes.lambda$onWorldLoad$0(EndBiomes.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at ru.betterend.registry.EndBiomes.onWorldLoad(EndBiomes.java:84)
	at ru.bclib.api.LifeCycleAPI.lambda$_runLevelLoad$2(LifeCycleAPI.java:142)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at ru.bclib.api.LifeCycleAPI._runLevelLoad(LifeCycleAPI.java:142)
	at net.minecraft.class_3218.handler$zmm000$bclib_onServerWorldInit(class_3218.java:3161)
	at net.minecraft.class_3218.<init>(class_3218.java:247)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:371)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:327)
	at net.minecraft.class_1132.method_3823(class_1132.java:72)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1368937632 bytes (1305 MiB) / 3472883712 bytes (3312 MiB) up to 15334375424 bytes (14624 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.50
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3090
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2204
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 40369.03
	Virtual memory used (MB): 21399.54
	Swap memory total (MB): 7680.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx14624m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		adorn: Adorn 3.1.0+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		advancementplaques: Advancement Plaques 1.4.3
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.4.6
		ae2: Applied Energistics 2 10.0.0-beta.3
		ae2wtlib: AE2WTLib 10.0.0-beta.3
		appleskin: AppleSkin mc1.18-2.2.0
		arcanus: Arcanus 1.25
		architectury: Architectury 3.4.9
		attributefix: AttributeFix 13.0.3
		authme: Auth Me 2.2.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axolotlitemfix: Axolotl Item Fix 1.1.3
		balm-fabric: Balm 2.4.0+0
		bannerpp: Banner++ 2.0.4+mc.1.18-rc4
		basicaiots: Basic AIOTs 1.3.3+1.18.1
		bcc: BetterCompatibilityChecker fabric-1.0.4
		bclib: BCLib 1.2.1
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.2
		betterend: Better End 1.0.0
		bettermounthud: Better Mount HUD 1.1.3
		bewitchment: Bewitchment 1.18-4
		bitsandchisels: BitsAndChisels 2.6.4
		blast: BLAST 1.8.2
		blockus: Blockus 2.3.4+1.18.1
		blue_endless_jankson: jankson 1.2.1
		boatcontainer: BoatContainer 1.0.4
		botania: Botania 1.18.1-427-FABRIC
		bountiful: Bountiful 2.0.1
		bowinfinityfix: Bow Infinity Fix rv11
		breakprogress: Break Progress 1.0.1
		buildinggadgets: st'ructure tools 1.0.8
		builtinservers: Builtin Servers 1.0.1-BETA+1.18
		cacao: Croptopia's Chocolaterie 0.5
		camsbackpacks: Cammie's Wearable Backpacks 2.7
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		capybara: Capybara 1.0.1
		cardinal-components-base: Cardinal Components API (base) 4.0.0
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0
		cardinal-components-item: Cardinal Components API (items) 4.0.0
		cardinal-components-level: Cardinal Components API (world saves) 4.0.0
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carrier: Carrier 1.9.0
		catwalksinc: Catwalks Inc. 1.1.0
		chalk: Chalk 1.2.1
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chisel: Chisel Refabricated 1.4.4
		chord: Chord 1.8.0+1.18-fabric
		clienttweaks: Client Tweaks 7.0.0
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps 8.0.4
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		conjuring: Conjuring 1.0.18+1.18
		controlling: Controlling For Fabric 9.0.8
		cosmetica: Cosmetica 0.3.2
		couplings: Couplings 1.7.1+1.18
		craftingcraft: CraftingCraft 11.0.0
		craftingtweaks: Crafting Tweaks 13.0.0
		croptopia: Croptopia 1.8.0
		croptosis: Croptosis 1.4.2
		dankstorage: Dank Storage 1.18.1-3.3
		dark-enchanting: Dark Enchanting 0.6.3+1.18
		darkpaintings: DarkPaintings 9.0.2
		dawn: Dawn API 3.2.0
		deathlog: DeathLog 0.2.4+1.18
		deepslatecutting: Deepslate Cutting 1.3.0
		defaultoptions: Default Options 14.0.0
		diggusmaximus: Diggus Maximus 1.5.2-1.18
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dml-refabricated: Deep Mob Learning: Refabricated 0.5.0-beta2
		dml-refabricated-base: DML: Refabricated - Base 0.5.0-beta2
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.5.0-beta2
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.5.0-beta2
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.5.0-beta2
		dmlsimulacrum: Deep Mob Learning: Simulacrum 0.5.0-beta2
		drinkbeer: Drink Beer 3.0.2
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchdesc: EnchantmentDescriptions 9.0.7
		entitybanners: Entity Banners 1.0.2-BETA+1.18
		equipmentcompare: Equipment Compare 1.2.9
		expandedstorage: Expanded Storage 7.3.6
		experiencebugfix: Experience Bug Fix 18
		extragenerators: Extra Generators 1.1.1-BETA+1.18
		fabric: Fabric API 0.45.1+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.8+d8e2078565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a14
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9514
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9514
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9514
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9514
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9514
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9514
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a14
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9514
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		fake-player-api: Fake Player API 0.3.0
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		farmingforblockheads: Farming for Blockheads 9.0.2
		fastbench: FastBench 1.18.1-3
		fastfurnace: FastFurnace 1.18-4
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric $version
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		floral_flair: Floral Flair 1.1.0
		fpsreducer: FPS Reducer 1.25-mc1.18
		gateofbabylon: Gate Of Babylon 1.5.1-1.17.1
		geckolib3: Geckolib 3.0.23
		glassential: Glassential 1.3.0
		go-fish: Go Fish 1.4.1-1.18.1
		goblintraders: Goblin Traders 1.4.1
		goldenhoppers: Golden Hoppers 1.2.0
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.1
		guild: Guild 0.3.6
		harvest_scythes: Harvest Scythes 2.4.0
		healthoverlay: Health Overlay 6.0.1
		horseinfo: Horse Info 0.4.1-1.18
		iceberg: Iceberg 1.0.27
		iknowwhatimdoing: I Know What I'm Doing 4.0.0
		impaled: Impaled 1.0.2
		impersonate: Impersonate 2.4.0
		improved-stations: Improved Stations 2.0.8
		incantationem: Incantationem 1.1.3+1.18.1
		indium: Indium 1.0.2-alpha1+mc1.18
		indrev: Industrial Revolution 1.13.2-BETA
		infusion_table: Infusion Table 1.0.5
		inmis: Inmis 2.4.0-1.18
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.2.1
		inventorysorter: Inventory Sorter 1.8.3-1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.3
		iron-jetpacks: Iron Jetpacks 0.4.3
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kambrik: Kambrik 3.0.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.4-BETA+1.18
		kjsextras: KubeJS Extras 1.5.0
		kleeslabs: KleeSlabs 11.0.0
		ktdatataglib: KtDataTagLib 1.6.4-1
		kubejs: KubeJS 1801.4.0-build.263
		kyrptconfig: Kyrpt Config 1.3.4-1.18
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.1.5
		libblockattributes_core: LibBlockAttributes (Core) 0.10.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.10.0
		libblockattributes_items: LibBlockAttributes (Items) 0.10.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.2.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lifts: Lifts 1.4-BETA+1.18
		lightoverlay: Light Overlay 6.0.4
		lithium: Lithium 0.7.7
		lovely_snails: Lovely Snails 1.0.3+1.18
		lumiwool: Luminous Wool 1.2.2
		magna: Magna 1.7.0-1.18-pre1
		maybe-data: Maybe data 1.0.1-1.17
		maybe-more-data: Maybe More Data 1.0.0-1.18
		megane: megane 6.2.0
		megane-applied-energistics-2: megane-applied-energistics-2 6.2.0+10.0.0-alpha.1
		megane-base: megane-base 6.2.0
		megane-dml-simulacrum: megane-dml-simulacrum 6.2.0+0.5.0-beta2
		megane-extra-generators: megane-extra-generators 6.2.0+1.1.1-BETA-1.18
		megane-fabric-transfer: megane-fabric-transfer 6.2.0+1.5.4-b4f4f6cda9
		megane-industrial-revolution: megane-industrial-revolution 6.2.0+1.13.1-BETA
		megane-kibe: megane-kibe 6.2.0+1.9.4-BETA-1.18
		megane-lib-block-attributes: megane-lib-block-attributes 6.2.0+0.10.0
		megane-modern-industrialization: megane-modern-industrialization 6.2.0+1.0.0-alpha.02
		megane-reborn-core: megane-reborn-core 6.2.0+5.1.0-beta.2
		megane-runtime: megane-runtime 6.2.0
		megane-team-reborn-energy: megane-team-reborn-energy 6.2.0+2.0.0-beta1
		megane-tech-reborn: megane-tech-reborn 6.2.0+5.1.0-beta.2
		megane-vanilla: megane-vanilla 6.2.0+1.18.1
		megane-wireless-networks: megane-wireless-networks 6.2.0+1.4.0
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		mocolors: Mo' Colors 1.3.0
		modern_industrialization: Modern Industrialization 1.0.3
		modmenu: Mod Menu 3.0.1
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousetweaks: Mouse Tweaks 2.20
		mtmechs: Magitek Mechs 1.0.10
		mythic-mounts: Mythic Mounts 1.18-4.0
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		nears: Nears 1.1.2
		netherportalfix: NetherPortalFix 9.0.0
		ninjaphenix_container_lib: NinjaPhenix's Container Library 1.2.10
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		noanglebrackets: NoAngleBrackets 1.1.0
		omega-config: OmegaConfig 1.1.0
		onastick: On A Stick 2.0.0
		org_anarres_jcpp: jcpp 1.4.14
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		owo: oωo 0.3.13+1.18
		patchouli: Patchouli 1.18.1-63-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		phosphor: Phosphor 0.8.1
		playerabilitylib: Pal 1.5.0
		pling: Pling 1.5.0
		plushies: Plushie Mod 1.1
		promenade: Promenade 2.4.0
		quickshulker: Quick Shulker 1.3.3-1.18
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0-beta.4
		redstonebits: Redstone Bits 1.6.2
		replanter: Replanter 1.3
		repurposed_structures: Repurposed Structures 3.2.0+1.18.1
		respawnablepets: Respawnable Pets 1.18-1
		rhino: Rhino 1800.1.7-build.92
		roughlyenoughitems: Roughly Enough Items 7.1.357
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		shulkerutils: shulkerutils 1.0.4-1.18
		simpleteleporters: Simple Teleporters 2.3.0
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.2
		slotlock: SlotLock 1.0.4-BETA+1.18
		smootherbedrock: Smoother Bedrock 1.0.3
		sodium: Sodium 0.4.0-alpha5+build.9
		someforgepatchesported: Some Forge Patches Ported 1.0.2
		spectrum: Spectrum 1.2.1-1.18.1-midgame2
		stacc: Stacc 1.2.3
		staffofbuilding: Staff of Building 1.4.1-1.18.1
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.4.1
		team_reborn_energy: Energy 2.1.0
		techreborn: Tech Reborn 5.1.0-beta.4
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		thonkutil: ThonkUtil 1.3
		toolstats: ToolStats 8.0.1
		tooltipfix: ToolTip Fix 1.0.4-1.18
		totemmod: Wither Totems Mod 0.3.4-1.18-rc2
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.0
		transportables: Transportables 1.1
		trapexpansion: Trap Expansion 1.3.3
		trashslot: TrashSlot 11.0.0
		trinkets: Trinkets 3.1.0
		urns: Urns 1.0.1
		vanilla-hammers: Vanilla Hammers 3.2.0-1.18.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		villager-hats: Villager Hats Mod 1.2.1
		visuality: Visuality 0.4.0
		waystones: Waystones 2.4.1
		wilderworld: WilderWorld 1.0.0
		winterly: Winterly 0.3.1
		wirelessnetworks: Wireless Networks 1.4.1
		wmitaf: WMITAF 2.2.0
		wolveswitharmor: Wolves With Armor 1.7.0-1.18
		wthit: wthit 4.4.0
		xaerominimap: Xaero's Minimap 21.23.0
		xaeroworldmap: Xaero's World Map 1.19.0
		yigd: You're in Grave Danger 1.2.10
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by dandin87** [comment]
Looks like old worlds will need to have their level.dat manually modified, unfortunately.
https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source

**Comment by LianLian2001** [comment]
> Looks like old worlds will need to have their level.dat manually modified, unfortunately. https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source

>
I created the world in 0.2.1 and upgraded from 0.2.5 to 0.2.7 today, is this required for all versions before 0.2.7?

**Comment by dandin87** [comment]
Correct. Idk why Better End doesn't just force change it, as I am pretty sure that's what it used to do when we added it to AoF3, and AoF4. We might try to have someone make a script that does this automatically, because its quite the hassle for the avg player.

**Comment by LianLian2001** [comment]
> Correct. Idk why Better End doesn't just force change it, as I am pretty sure that's what it used to do when we added it to AoF3, and AoF4. We might try to have someone make a script that does this automatically, because its quite the hassle for the avg player.



> Correct. Idk why Better End doesn't just force change it, as I am pretty sure that's what it used to do when we added it to AoF3, and AoF4. We might try to have someone make a script that does this automatically, because its quite the hassle for the avg player.

Yes, after reading tutor ten times over, I decided to go out for a McDonald's burger to cool down my hot head because I still hadn't understood exactly what I was supposed to do.

**Comment by dandin87** [comment]
If you post the level.dat I can fix it. Might be easier if you come on discord.

**Comment by DV8ZXPru** [comment]
> 



> https://github.com/paulevsGitch/BetterEnd/wiki/Tutorials#how-to-fix-wrong-biome-source

In this wiki did not update step 6. There the values ​​changed from betterend: better_end_biome_source to bclib: end_biome_source and also in biome_source for Nether, you need to remove the tag preset: minecraft: nether. Add tag seed: "your seed" instead.  Type tag for nether also changes to bclib:nether_biome_source

see pic: left - new save 0.2.7 ver, right old 0.2.5 ver
![fix_world](https://user-images.githubusercontent.com/2900356/147942035-eec61166-e420-4bfc-96f9-14793b9473a1.png)

After such changes, the save loaded normally.

**Comment by Cavecanem** [comment]
> In this wiki did not update step 6. There the values ​​changed from betterend: better_end_biome_source to bclib: end_biome_source and also in biome_source for Nether, you need to remove the tag preset: minecraft: nether. Add tag seed: "your seed" instead. Type tag for nether also changes to bclib:nether_biome_source

This worked perfectly! No crash, and I can still enter the Nether. Thanks a bunch :)

**Comment by tcm151** [comment]
I had the same issue, and I tried to edit the level.dat file but was unsuccessful. What I did to get around it was generate a new world with the same seed as my old world (0.2.5) on the new version (0.2.7). Then copy the worldGenSettings from the level.dat file from the new world and paste then into the old world level.dat file using NBTExplorer and that solved my issue

**Comment by ImAK9** [comment]
fixed with 0.2.8+
