### ISSUE TITLE
Dank Storage Broken Search Feature

### ISSUE THREAD

**Issue by Maseudo** [TeamAOF/All-of-Fabric-5#59]
Just updated my client and server to 0.2.7 and am running into an issue where I can't close my dank storage with E anymore. Mostly annoying but seems to be some kind of stuck search feature, that as far as I can tell doesn't actually do anything
![2022-01-04_00 36 27](https://user-images.githubusercontent.com/46875906/148019054-c72b07e0-5686-494a-b946-313f2212bb9a.png)
Never had this problem before the update.

**Comment by ImAK9** [comment]
Cant be closed with ESC?
