### ISSUE TITLE
The end does not load properly

### ISSUE THREAD

**Issue by BiggZee** [TeamAOF/All-of-Fabric-5#60]
Since updating to 0.2.7, the end has refused to load properly. BetterEnd assets do not load, only a select few texures and mobs. The end city is almost non-existent. No end portals spawn either. I have deleted the DIM1 multiple times and edited the level.dat. Just for testing purposes I created a fresh single player world with default settings and am still having the same issues. Any help is appreciated.

**Comment by dandin87** [comment]
Read through this issue. You have to nbt edit the level.dat file 
https://github.com/TeamAOF/All-of-Fabric-5/issues/55
