### ISSUE TITLE
Crash when hovering over the handheld steam mining drill from MI.

### ISSUE THREAD

**Issue by DiegoFValdez** [TeamAOF/All-of-Fabric-5#64]
Modern Industrialization has a handheld steam mining drill and I am now crashing anytime I hover over it with mouse cursor.
Only happened after updated to version 2.8 of the modpack.

Modpack version: 2.8

Crashlog: https://pastebin.com/VTcwDis3

**Comment by ImAK9** [comment]
Update to 0.2.9
