### ISSUE TITLE
Target Dummy from MmmMmmMmmMmm is a server destroying WMD.

### ISSUE THREAD

**Issue by RotatingBuffalo** [TeamAOF/All-of-Fabric-5#66]
The Target Dummy, when shot, results in hard server crashes, likely as a result of an interaction with Lithium, judging from the logs.
Seemingly any EntityCollision with the dummy will instantly crash the server, meaning if a player shoots the dummy with an arrow, the server will crash every single time that chunk is loaded.
Upon removing MmmMmmMmmMmm, this bug was fixed for my server.

[2022-01-07-3.log](https://github.com/TeamAOF/All-of-Fabric-5/files/7831738/2022-01-07-3.log) 

The issue on MmmMmmMmmMmm's repo https://github.com/MehVahdJukaar/DuMmmMmmy1.16/issues/5

**Comment by MehVahdJukaar** [comment]
So I can't figure this out on my own. Could anybody from Lithium dev team help me fix this, assuming it's an issue on my end?
I've updated the Fabric github repo here https://github.com/MehVahdJukaar/DummyFabric1.16
