### ISSUE TITLE
Crash when using the Spectrum Crafting Table

### ISSUE THREAD

**Issue by Rakkis157** [TeamAOF/All-of-Fabric-5#70]
Was testing a few things in my creative world. Putting items into the Spectrum Crafting Table sometimes causes the game to crash.

[crash-2022-01-08_16.07.20-client.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/7832864/crash-2022-01-08_16.07.20-client.txt)
[latest.log](https://github.com/TeamAOF/All-of-Fabric-5/files/7832865/latest.log)

**Comment by ImAK9** [comment]
That's due to AE2 Things which was updated tih 0.2.9 hotfix

**Comment by Rakkis157** [comment]
Ah.
Is the hotfix out already?

**Comment by Monster-Zer0** [comment]
yes. or just update AE2 Things
