### ISSUE TITLE
Chunk disappears when placing Industrial Revolution Rancher (AOF V0.2.9)

### ISSUE THREAD

**Issue by neonbladez2** [TeamAOF/All-of-Fabric-5#71]
So when placing a Industrial Revolution Rancher no matter which tier it causes the client to crash and which force unloads the chunks around the rancher. Additionally, the 8 surrounding chunks (9 chunks total, a 3x3 area) are visually invisible, but otherwise still able to be interacted with the center. Chunk even vanishes from the minimap Additionally, mobs and entities that enter these chunks have their AI break so long as they're registered within the chunk. If you hit something, it stays red It also jitters endlessly, Cannot walk as no movement occurs. As well as flashing screens of the chunks because of this. IndRev version 1.13.4-BETA.jar is the version currently causing this.

[crash-2022-01-08_23.21.41-client.txt](https://github.com/TeamAOF/All-of-Fabric-5/files/7833076/crash-2022-01-08_23.21.41-client.txt)

![Indrev](https://user-images.githubusercontent.com/91413148/148641760-78885288-24b0-4ccd-a72a-89871afd4bea.png)

**Comment by neonbladez2** [comment]
Aegis System — Today at 12:07 AM

Update: all marks have been tested and confirmed to crash client-only while on a server

The thing is, even when another player is around, the block does not actually place, the client will simply crash while attempting to place

something even more fascinating is that I put one in a Block Placer from the Spectrum mod, and set that off
rancher did not place, however my client did not crash

upon attempting to open the activated block placer, my client crashed
it might have something to do with how the block leaves an inventory? idk

**Comment by k3nw4y** [comment]
https://github.com/GabrielOlvH/Industrial-Revolution/commit/2454edd6176a3be1c21a543cc6da1f24b24fa8e5
