### ISSUE TITLE
Mod Suggestion: Terrestria/Traverse

### ISSUE THREAD

**Issue by tcm151** [TeamAOF/All-of-Fabric-5#73]
https://www.curseforge.com/minecraft/mc-mods/terrestria
https://www.curseforge.com/minecraft/mc-mods/traverse

**Comment by tcm151** [comment]
nvm there is no version supported for 1.18, maybe when it is ready

**Comment by tcm151** [comment]
https://github.com/TerraformersMC/Terrestria/pull/266

Seems like there is a active pull request being updated as of 8 hours ago to bring the mods up to 1.17. I am not sure how difficult the transition from 1.17 to 1.18 is tho

**Comment by NebelNidas** [comment]
Once we have a proper Biome API, I'll look into porting it 👍

**Comment by dandin87** [comment]
fyi, this is basically the start of Biome API.
https://github.com/Patbox/biome-api
