### ISSUE TITLE
[Recommendation] CC: Tweaked

### ISSUE THREAD

**Issue by Sectly** [TeamAOF/All-of-Fabric-5#83]
I would love it if [Computer Craft: Tweaked](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked) gets added to **AOF5** also since its one of my favorite mods!

Also keep up the good work!

Thanks,
Sectly.

**Comment by ImAK9** [comment]
forge mod

**Comment by MoriyaShiine** [comment]
They probably meant [CC: Restitched](https://www.curseforge.com/minecraft/mc-mods/cc-restitched), the fabric port of CC: Tweaked
