### ISSUE TITLE
Heaven's Wings Anchor Augment from goml working outside the claim

### ISSUE THREAD

**Issue by Mecan0StarCrafter** [TeamAOF/All-of-Fabric-5#90]
Hi When I use the Heaven's Wings Anchor Augment in my goml claim if I get outside of the claim I can continue to fly. When I teleport to a home or do a rtp everything is normal. Also I can't see my claim outline with the goggle.

**Comment by k3nw4y** [comment]
Fixed in this commit
https://github.com/Patbox/get-off-my-lawn-server-sided/commit/33fdaedb3f73b3e3bcc632a653d1223cf7ed26f2
