### ISSUE TITLE
`/sort` does not work with Iron Chests

### ISSUE THREAD

**Issue by angeloanan** [TeamAOF/All-of-Fabric-5#95]
When using the command `/sort` on a chest from the Iron Chests mod, the command does not detect the said chest thus failing to sort the chest. 

Possibly an upstream mod issue.

**Comment by NinjaPhenix** [comment]
If anyone is able to tell mewhich mod the `/sort` command is from I'd take a look into if any fix on my end is possible.

**Comment by angeloanan** [comment]
Interestingly, opening the chest and manually sorting them (either using Middle Click or pressing R) works just fine.

**Comment by NinjaPhenix** [comment]
Seems to be an issue with expanded storage or perhaps a mixin, not sure when I'll get around to looking at this though.

**Comment by dandin87** [comment]
honestly, I don't know why they have this as a command. Sorting with a command instead of a button seems like something that should not be expected of players. If there is a way to disable the command I will do that in the pack.

**Comment by dandin87** [comment]
> Interestingly, opening the chest and manually sorting them (either using Middle Click or pressing P) works just fine.

Looks like this command was never implemented all the way.
https://github.com/kyrptonaught/Inventory-Sorter/issues/63
