### ISSUE TITLE
[Recommendation] CC: Restitched

### ISSUE THREAD

**Issue by Sectly** [TeamAOF/All-of-Fabric-5#96]
I would love it if [Computer Craft: Restitched](https://www.curseforge.com/minecraft/mc-mods/cc-restitched) gets added to AOF5 also since it's one of my favorite mods!

Also, keep up the good work!

Side Note: This is a [repost](https://github.com/TeamAOF/All-of-Fabric-5/issues/83) the last one got closed because I forgot to link the fabric version of CC: Tweaked! | (Thanks @MoriyaShiine)

Thanks,
Sectly.

**Comment by KaneHart** [comment]
#93

**Comment by Sectly** [comment]
> #93

Did not saw that when I looked at issues and i just reposted this one bec i send one before and it got closed bec i forgot to link the fabric version of it.
